#+title: Emacs Configuration
#+author: Peter Borocz
#+email: peter.borocz@gmail.com
#+options: num:nil
#+property: header-args :tangle config.el

* INBOX
** TODO Would love to try out [[https://github.com/honmaple/emacs-maple-modeline][honmaple/emacs-maple-modeline: Beautiful emacs modeline]] but can't get quelpa install to work well.
** TODO Install and test out ClaudeCode in [[https://github.com/mindslost/claude-code-emacs][emacs]].
** TODO Review: [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][Using use-package the right way - (think)]] and update vv :init, :config etc.
** TODO Install and integrate [[https://languagetool.org/][LanguageTool (grammar checker)]] into [[https://github.com/PillFall/languagetool.el][emacs]].
** TODO [[https://github.com/pizzatorque/uv-menu/blob/master/uv.el][uv-menu/uv.el at master · pizzatorque/uv-menu · GitHub]]
* Base Editing Environment
** tune garbage collection
#+begin_src emacs-lisp
  (use-package gcmh
    :straight (gcmh :type git :host github :repo "emacsmirror/gcmh")
    :init
    (gcmh-mode 1)
    )
#+end_src
** emacs
#+begin_src emacs-lisp
  (use-package emacs
    :init
    (setq
     ad-redefinition-action                 'accept   ; https://andrewjamesjohnson.com/suppressing-ad-handle-definition-warnings-in-emacs/
     auto-save-default                      nil       ; Stop creating autosaving files (we setup/use bbatsov's auto-save instead)
     blink-cursor-blinks                    2
     blink-cursor-delay                     0.0
     blink-cursor-interval                  0.3       ; Default is 0.5
     blink-cursor-mode                      1
     create-lockfiles                       nil       ; We don’t need lockfiles since were ONLY single-user!
     column-number-mode                     t
     debug-on-error                         nil
     debug-on-signal                        nil
     debug-on-quit                          nil
     default-directory                      (concat (getenv  "HOME") "/")
     delete-by-moving-to-trash              t         ; Goes with setq trash-directory setting below
     fill-column                            96
     font-lock-maximum-decoration           t
     frame-title-format                     '("%b " (:eval (format-time-string " %Y-%m-%d %H:%M")))
     global-auto-revert-non-file-buffers    t         ; Revert Dired and other buffers on changes
     global-font-lock-mode                  1
     indent-tabs-mode                       nil       ; Make sure spaces are used when indenting anything!
     inhibit-compacting-font-caches         t         ; https://github.com/sabof/org-bullets/issues/11#issuecomment-439228372
     inhibit-default-init                   t
     inhibit-splash-screen                  t
     initial-scratch-message                nil       ; Start scratch buffers empty..
     make-backup-files                      nil       ; Stop creating backup~ files
     ring-bell-function                     'ignore
     search-highlight                       t
     sentence-end-double-space              nil       ; Period single space ends sentence
     switch-to-buffer-obey-display-actions  t         ; https://www.masteringemacs.org/article/demystifying-emacs-window-manager: Switching Buffers
     trash-directory                        "~/.Trash"; Goes with delete-by-moving-to-trash above
     uniquify-after-kill-buffer-p           t         ; Rename after killing uniquified
     uniquify-buffer-name-style             'forward  ; https://github.com/bbatsov/prelude
     uniquify-ignore-buffers-re             "^\\*"    ; Don't muck with special buffers
     uniquify-separator                     "/"
     use-dialog-box                         nil       ; Don't popup UI dialogs when prompting
     use-short-answers                      t         ; Used for emacs >= 29.
     user-full-name                         "Peter Borocz"
     vc-follow-symlinks                     t         ; https://stackoverflow.com/questions/15390178/emacs-and-symbolic-links#15391387
     visible-bell                           t
     word-wrap                              nil
     x-stretch-cursor                       t         ; https://pragmaticemacs.wordpress.com/2017/10/01/adaptive-cursor-width/
     yank-excluded-properties              't         ; Clipboard yank is pasting graphics from Microsoft instead of text...strip all properties!
     ))

  ;; Buffer local, can't simply use the setq above.
  (setq-default truncate-lines t)

  ;; Miscellaneous settings..
  (global-auto-revert-mode  1) ;; refresh a buffer if changed on disk
  (recentf-mode             1) ;; remember recently edited files (M-x recentf-open-files to show)

  ;; In emacs 29+, seems like toggle-debug-on-quit is flipped to T by default,
  ;; causing C-g for minibuffer-quit to start the debugger(!). We don't want that.
  ;; per https://emacs.stackexchange.com/questions/70177/how-can-i-apply-toggle-debug-on-quit-ignore-debugger-entered-lisp-error/70180
  (add-to-list 'debug-ignored-errors 'minibuffer-quit)

  ;; Define all aliases for buffer management
  (defalias 'list-buffers 'ibuffer)  ; Use ibuffer default for all buffer management

  ;; Don't let Emacs suspend by getting rid of pesky "\C-z" and "\C-x\C-z" annoying minimize
  (unbind-key "C-z")
  (unbind-key "M-z")

  ;; Scrolling HT: http://home.thep.lu.se/~karlf/emacs.html
  (setopt scroll-step                     1)
  (setopt scroll-conservatively           100000)	;; Marker distance from center (don't jump to center).
  (setopt scroll-preserve-screen-position 1)	;; Try to keep screen position when PgDn/PgUp.
  (setopt scroll-margin                   0)	;; Start scrolling when marker at top/bottom.
  (setopt mouse-wheel-scroll-amount       '(1))	;; Mouse scroll moves 1 line at a time, instead of 5 lines.
  (setopt mouse-wheel-progressive-speed   nil)	;; On a long mouse scroll keep scrolling by 1 line.

  (use-package paren
    :defer 1
    :init
    (setopt show-paren-delay 0)  ; We want matching parens to show immediately
    :config
    (show-paren-mode t))

  (use-package exec-path-from-shell
    :config
    (exec-path-from-shell-initialize))
#+end_src
** enlight (startup dashboard)
#+begin_src emacs-lisp
  (defun pb/set-enlight-font ()
    (interactive)
    (setopt buffer-face-mode-face '(:height 220))
    (buffer-face-mode))

  (use-package enlight
    :straight (enlight :type git :host github :repo "ichernyshovvv/enlight")
    :custom
    (enlight-content
     (concat
      (propertize "DASHBOARD" 'face 'bold )
      "\n\n"
      (enlight-menu
       '(("Active Projects"
	    ("Investment Reporting"      (dired "~/Repository/10-19 Development/10 Development/10.28 investing")                   "t")
	    ("QYX - Python Code Quality" (dired "~/Repository/10-19 Development/10 Development/10.27 python-code-quality")         "q")
	    ("Sports - Optimus Ludos"    (dired "~/Repository/10-19 Development/10 Development/10.01 optimus_ludos")               "o")

	    ("Recipes - Coctione Libri"  (dired "~/Repository/10-19 Development/10 Development/10.23 coctione_libri")              "c")
	    ("Health Activity Dashboard" (dired "~/Repository/10-19 Development/10 Development/10.06 health-activity-dashboard")   "a")
	    ;; ("Information Mapping (Typst)"   (dired "~/Repository/10-19 Development/10 Development/10.25 compositionem_informationum") "i")
	    ;; ("Pecunia Exemplar"              (dired "~/Repository/10-19 Development/10 Development/10.21 pecunia_exemplar")            "u")
	    )
	   ("Org"
	    ("Projects" (find-file "~/Repository/00-09 System/01 Org/projects.org")    "p")
	    ("Journal"  (find-file "~/Repository/00-09 System/01 Org/journal.org")     "j")
	    ("GTD"      (find-file "~/Repository/00-09 System/01 Org/gtd.org")         "g")
	    )
	   ("Directories"
	    ("-Root-"      (dired "~/Repository")                                  "r")
	    ("Development" (dired "~/Repository/10-19 Development/10 Development") "d")
	    ("Money"       (dired "~/Repository/20-29 Money")                      "m")
	    ("Health"      (dired "~/Repository/30-39 Health")                     "h")
	    )
	   ("Utilities"
	    ("Emacs Configuration" (find-file "~/.emacs.d/config.org")                                 "e")
	    ("Python Reference"    (find-file "~/Repository/00-09 System/01 Org/reference/python.org") "y")
	    ("*Claude*"            (command-execute 'gptel)                                            "a")
	    )

	   ))))

    :config
    (setopt enlight-buffer-name "HOME") ;; Defaults to *light-dashboard* but I want something a bit more ?personal?

    ;; <2026-02-18 Wed> Don't need to do this, standard font size is *fine*.
    ;;(add-hook 'enlight-mode-hook 'pb/set-enlight-font)

    (enlight-open)
    )
#+end_src
** anzu
Highlight global-search-replace strings dynamically.
#+begin_src emacs-lisp
  (use-package anzu
    :defer 5
    :straight t
    :config
    (global-anzu-mode)
    )
#+end_src
** COMMENT buffer-terminator
[[https://github.com/jamescherti/buffer-terminator.el][GitHub - jamescherti/buffer-terminator.el: buffer-terminator - Safely Termina...]]
<2026-04-30 Thu> Turning this off, seems to be have gotten very aggressive recently!
#+begin_src emacs-lisp
  (use-package buffer-terminator
    :ensure t
    :custom
    (buffer-terminator-inactivity-timeout (* 90 60)) ;Override default of 30' to be 90'
    :config
    (setopt buffer-terminator-rules-alist
	      '((keep-buffer-property . special)
		(keep-buffer-property . process)
		(keep-buffer-property . visible)
		(kill-buffer-property . inactive)
		(keep-buffer-name     . ("*Claude*"))
		))
    (buffer-terminator-mode 1))
#+end_src
** hungry-deletes
[[https://github.com/hrehfeld/emacs-smart-hungry-delete]]
#+begin_src emacs-lisp
  (use-package smart-hungry-delete
    :defer 10
    :bind (
       ([remap delete-char]                   . smart-hungry-delete-forward-char)
       ([remap org-delete-char]               . smart-hungry-delete-forward-char)
       ([remap backward-delete-char-untabify] . smart-hungry-delete-backward-char)
       ([remap delete-backward-char]          . smart-hungry-delete-backward-char)
       )
    :init (smart-hungry-delete-add-default-hooks)
    )
#+end_src
** dired
[[https://github.com/MatthewZMD/.emacs.d]]
[[https://www.emacswiki.org/emacs/DiredSortDirectoriesFirst][Sort dired listings with directories first]]
*** dired
#+begin_src emacs-lisp
  (defun pb/dired-create-empty-directory ()
    "Wrapper to dired-create-directory to avoid minibuffer completion."
    ;; https://emacs.dyerdwelling.family/emacs/20240922201246-emacs--efficient-directory-and-file-management-with-dired-in-emacs/
    (interactive)
    (let ((search-term
	     (read-from-minibuffer "Create empty directory : ")))
      (dired-create-directory search-term)))

  ;; https://lmno.lol/alvaro/hide-another-detail
  (defun pb/hide-dired-details-include-all-subdir-paths ()
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward dired-subdir-regexp nil t)
	  (let* ((match-bounds (cons (match-beginning 1) (match-end 1)))
		 (path (file-name-directory (buffer-substring (car match-bounds)
							      (cdr match-bounds))))
		 (path-start (car match-bounds))
		 (path-end (+ (car match-bounds) (length path)))
		 (inhibit-read-only t))
	    (put-text-property path-start path-end
			       'invisible 'dired-hide-details-information)))))

  (use-package dired
    :straight (:type built-in)

    :bind (:map dired-mode-map
	  ("C-x j" . dired-jump-other-window)
	  ("e"     . dired-toggle-read-only) ; Inline filename editing (C-c C-c when done)
	  ("q"     . kill-current-buffer)    ; Instead of simply closing the buffer
	  ("."     . dired-up-directory)
	  ("F"     . dired-create-empty-file)
	  ("D"     . pb/dired-create-empty-directory)
	  )

    :config
    (setopt auto-revert-verbose                        nil ;; Auto refresh Dired, but be quiet about it
      dired-create-destination-dirs-on-trailing-dirsep t
      dired-dwim-target                                t
      dired-create-destination-dirs                    'ask
      dired-hide-details-mode                          nil
      dired-kill-when-opening-new-dired-buffer         t
      dired-listing-switches                           "-Al"
      dired-recursive-copies                           'always
      dired-recursive-deletes                          'always
      dired-use-ls-dired                               t
      dired-vc-rename-file                             t ;; https://xenodium.com/emacs-git-rename-courtesy-of-dired/
      global-auto-revert-non-file-buffers              t
      insert-directory-program                         "/usr/local/bin/gls"
      wdired-allow-to-change-permissions               t
      )

    :hook (
	   (dired-mode         . dired-hide-details-mode)
	   (dired-after-readin . pb/hide-dired-details-include-all-subdir-paths)
	   )
    )

  (when (string= system-type "darwin")
    (setopt dired-use-ls-dired nil))
#+end_src
*** dired-gitignore
Toggle between showing just ".git-ted" files and all files.
#+begin_src emacs-lisp
  (use-package dired-gitignore
    :after dired
    :config
    (define-key dired-mode-map (kbd "H") #'dired-gitignore-global-mode) ;; into your startup files. Then you will hide and show the gitignored files in a dired buffer by hitting the H key.
    )
#+end_src
*** dired-xah
#+begin_src emacs-lisp
  (defun xah-dired-sort ()
    "Sort dired dir listing in different ways.
  Prompt for a choice.
  Works in linux, MacOS, Microsoft Windows.

  URL `http://xahlee.info/emacs/emacs/dired_sort.html'
  Created: 2018-12-23
  Version: 2025-01-05"
    (interactive)
    (let ((xmenu '(("date" . "-Al -t")
		   ("size" . "-Al -S")
		   ("name" . "-Al ")
		   ("dir" . "-Al --group-directories-first")))
	  xsortBy)
      (setq xsortBy (completing-read "Sort by (default date):" xmenu nil t nil nil (caar xmenu)))
      (dired-sort-other (cdr (assoc xsortBy xmenu)))))
#+end_src
*** dired-subtree
#+begin_src emacs-lisp
  (use-package dired-subtree
    :after dired
    :config
    (bind-key "<tab>" #'dired-subtree-toggle dired-mode-map)
    (bind-key "<backtab>" #'dired-subtree-cycle dired-mode-map))
#+end_src
** [[https://github.com/Wilfred/helpful][helpful]] (better help commands)
Improve quality of most-used C-h methods.
#+begin_src emacs-lisp
  (use-package helpful
    :demand t
    :bind
    ;; Note that the built-in `describe-function' includes both functions
    ;; and macros. `helpful-function' is functions only, so we provide
    ;; `helpful-callable' as a drop-in replacement.
    ("C-h f" . helpful-callable)
    ("C-h v" . helpful-variable)
    ("C-h k" . helpful-key)
    ("C-h x" . helpful-command)

    ;; I also recommend the following keybindings to get the most out of helpful:
    ;; Lookup the current symbol at point. C-c C-d is a common keybinding
    ;; for this in lisp modes.
    ("C-c C-d" . helpful-at-point)

    ;; Look up *F*unctions (excludes macros).
    ;;
    ;; By default, C-h F is bound to `Info-goto-emacs-command-node'. Helpful
    ;; already links to the manual, if a function is referenced there.
    ("C-h F"  . helpful-function)
    )

#+end_src
** indentation
*** outline-indent
#+begin_src emacs-lisp
  (use-package outline-indent
    :straight (outline-indent :type git :host github :repo "jamescherti/outline-indent.el")

    :custom
    (outline-indent-ellipsis " ▼ ")

    :config
    (setopt outline-blank-line t)
    )
#+end_src
*** COMMENT kirigami
<2026-04-30 Thu> After getting used to Ctrl-Tab, too much mental-cost learning these new mappings.
#+begin_src emacs-lisp
  (use-package kirigami
    :ensure t

    :config
    (global-set-key (kbd "C-c k o")   'kirigami-open-fold)     ; Open fold at point
    (global-set-key (kbd "C-c k O")   'kirigami-open-fold-rec) ; Open fold recursively
    (global-set-key (kbd "C-c k m")   'kirigami-close-folds)   ; Close all folds
    (global-set-key (kbd "C-c k c")   'kirigami-close-fold)    ; Close fold at point
    (global-set-key (kbd "C-c k r")   'kirigami-open-folds)    ; Open all folds
    (global-set-key (kbd "C-c k TAB") 'kirigami-toggle-fold)   ; Toggle fold at point
    )
#+end_src
** pbcopy (allow interaction with MacOS clipboard and kill/yank ring)
#+begin_src emacs-lisp
  (use-package pbcopy
    :defer t
    )
#+end_src
** saveplace (save last-editing location)
#+begin_src emacs-lisp
  (use-package saveplace
    :defer 1

    :config
    (setq-default save-place t)

    :init
    (save-place-mode 1)
    )
#+end_src
** super-save (save on buffer switch)
[[https://github.com/bbatsov/super-save][GitHub - bbatsov/super-save: Save Emacs buffers when they lose focus]]:
Best description is from package site itself: "super-save auto-saves
your buffers, when certain events happen - e.g. you switch between
buffers, an Emacs frame loses focus, etc. You can think of it as both
something that augments and replaces the standard auto-save-mode."
#+begin_src emacs-lisp
  (use-package super-save
    :defer 1

    :config
    (super-save-mode 1)
    )
#+end_src
** unfill
https://github.com/purcell/unfill
 #+begin_src emacs-lisp
   (use-package unfill
     :defer 1

     :bind (("M-Q" . unfill-paragraph))
     )
#+end_src
** whitespace-cleanup
#+begin_src emacs-lisp
  (use-package whitespace-cleanup-mode
    :defer 1

    :init
    (setopt whitespace-cleanup-mode-only-if-initially-clean nil)

    :config
    (global-whitespace-cleanup-mode 1)
    )
#+end_src
** yasnippet
While the majority of the time, I don't rely on snippets, there are a very select /few/
that I consider worthwhile, thus, keep use of yasnippets for now (but make sure they don't
expand within comments!)
#+begin_src emacs-lisp
  ;; Don't do snippet expansion within comments/docstrings.
  ;; (https://stackoverflow.com/questions/25521897/how-to-never-expand-yasnippets-in-comments-and-strings)
  (defun pb/no-expand-in-comment_string ()
    (setopt yas-buffer-local-condition
      '(if (nth 8 (syntax-ppss)) ;; non-nil if in a string or comment
       '(require-snippet-condition . force-in-comment)
     t)))

  (use-package yasnippet
    :defer 1
    :config

    ;; Bind `SPC' to `yas-expand' when snippet expansion available (it will still call `self-insert-command' otherwise)
    (define-key yas-minor-mode-map (kbd "SPC") yas-maybe-expand)

    ;; Use the method above to keep snippets only when we're writing code or in
    (add-hook 'python-ts-mode-hook   #'yas-minor-mode)
    (add-hook 'python-base-mode-hook #'yas-minor-mode)
    (add-hook 'text-mode-hook        #'yas-minor-mode)
    (add-hook 'prog-mode-hook        #'pb/no-expand-in-comment_string)
    (yas-global-mode 1)
    (yas-reload-all)
    )
#+end_src
* Display
** color-theme(s)
*** Leuven (light)
#+begin_src emacs-lisp
  (load-theme 'leuven t)
#+end_src
*** COMMENT Modus Operandi (light)
Note: ARCHIVE section below includes a LOT of sample configuration tweaks!
#+begin_src emacs-lisp
  (load-theme 'modus-operandi t)
#+end_src
*** COMMENT Gruvbox (dark)
#+begin_src emacs-lisp
  ;; HT to https://emacsredux.com/blog/2025/02/13/customizing-color-themes/ obo :custom-face!
  (use-package gruvbox-theme
    :demand t
    :config
    (load-theme 'gruvbox-dark-medium t)
    (custom-set-faces
     '(org-level-1            ((t (:height 1.15))))
     '(org-level-2            ((t (:height 1.10))))
     '(org-level-3            ((t (:height 1.05))))
     '(org-level-4            ((t (:foreground "#b8bb26"))))
     '(org-level-5            ((t (:foreground "#fb4933"))))
     '(org-level-6            ((t (:foreground "#666666"))))
     '(font-lock-doc-face     ((t (:foreground "#666666"))))
     '(font-lock-comment-face ((t (:foreground "#666666"))))
     '(org-document-title     ((t (:height 1.5 :underline nil))))
     )
    )
#+end_src
** font(s)
Interactive font scaling:
  - For all frames     -> M-x increase-font-size/decrease-font-size (C-+ and C-- respectively)
  - For current buffer -> M-x text-scale-adjust

 Which one is currently displayed?
   - M-x describe-font <cr> <cr>

 Set a new font interactively:
   - M-x set-frame-font (Pick from list!)

 History of fonts actually tried for more than one day:

 "-*-DM Mono-normal-normal-normal-*-%d-*-*-*-m-0-iso10646-1"
 "-*-Astigmata-medium-normal-normal-*-%d-*-*-*-p-0-iso10646-1"
 "-*-Inconsolata-regular-normal-normal-*-%d-*-*-*-m-0-iso10646-1"
 "-*-Cascadia Code-ultralight-normal-normal-*-%d-*-*-*-m-0-iso10646-1"
 "-*-Noto Sans Mono-light-normal-normal-*-%d-*-*-*-p-0-iso10646-1" ; Valiant attempt! Almost a week with Noto Sans Mono but going back to SCP-NF due to the more "rounded" nature.
 "-*-Roboto Mono-light-normal-normal-*-%d-*-*-*-m-0-iso10646-1"
 "-*-Monaspace Argon-ultralight-normal-normal-*-%d-*-*-*-p-0-iso10646-1" ; Tried for a few days, like the idea of having different font-face to comments that are still mono but couldn't make it work.
 "-*-Red Hat Mono-light-normal-normal-*-%d-*-*-*-m-0-iso10646-1"
 "-*-Roboto Mono-light-normal-normal-*-%d-*-*-*-m-0-iso10646-1"
 "-*-Atkinson Hyperlegible Mono-ultralight-normal-normal-*-%d-*-*-*-m-0-fontset-auto5" ; Trying out 2025-11-10
 "-*-Maple Mono NF-ultralight-normal-normal-*-%d-*-*-*-m-0-iso10646-1" ; Keeper so far, one of the only other font families I've found that include light and ultra-light versions!
 "-*-Geist Mono-ultralight-normal-normal-*-%d-*-*-*-m-0-iso10646-1" ; Wow, used this for almost 2+ months!
 "-*-SauceCodePro Nerd Font Mono-light-normal-normal-*-%d-*-*-*-m-0-iso10646-1"

 #+begin_src emacs-lisp
  (setopt ns-use-thin-smoothing t)

  ;; Set my default font (always mono, even for org writing)
  (defvar pb/var-fixedwidth-font "-*-SauceCodePro Nerd Font Mono-regular-normal-normal-*-%d-*-*-*-m-0-iso10646-1")

  (defun pb/set-monitor-font-size ()
    "Set font for 4K monitor."
    (interactive)
    (set-frame-font (format pb/var-fixedwidth-font 18))
    )

  (defun pb/set-laptop-font-size ()
    "Set font for laptop display."
    (interactive)
    (set-frame-font (format pb/var-fixedwidth-font 14))
    )

  ;; Given the 2 methods above, set the font size based on where our Emacs is running at the moment:
  (if (display-graphic-p)
      (if (>= (x-display-pixel-width) 2000) ; Allow for somewhat lower resolutions than full 3840.
	  (pb/set-monitor-font-size)
	(pb/set-laptop-font-size)))
#+end_src
** frame-options
#+begin_src emacs-lisp
  (setq default-frame-alist '((background-color        . "#1d2021") ;; Same background color as our theme
			      (ns-appearance           . dark)
			      (ns-transparent-titlebar . t)))

  (set-window-scroll-bars (minibuffer-window) nil nil)
  (set-default-coding-systems 'utf-8)

#+end_src
** hl-line(+)
#+begin_src emacs-lisp
  (use-package hl-line
    :custom-face
    (hl-line ((t (:background "gray17"))))
  )
  (global-hl-line-mode)

  (use-package hl-line+
    :config
    (hl-line-when-idle-interval 0.5)
    (toggle-hl-line-when-idle   1))

#+end_src
** mode-line(s)
*** [[https://github.com/seagle0128/doom-modeline][doom]]
<2026-02-01 Sun> Resurrected as I wanted something a bit more informative than /mood-line/.
[[http://emacs.stackexchange.com/questions/13227/easy-way-to-give-the-time-its-own-face-in-modeline][http://emacs.stackexchange.com/questions/13227/easy-way-to-give-the-time-its-own-face-in-modeline]]
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :init
    (setq doom-modeline-minor-modes      nil
	  doom-modeline-time             t
	  doom-modeline-vcs-max-length   20
	  inhibit-compacting-font-caches t
	  nerd-icons-scale-factor        1.0
	  )
    :config
    (doom-modeline-mode 1))
#+end_src
** no-distraction
[[https://github.com/Artawower/no-distraction.el][GitHub - Artawower/no-distraction.el]]
#+begin_src emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/site-lisp/no-distraction.el")
  (require 'no-distraction)

  ;; (custom-set-faces
  ;;  '(gray-face ((t (:foreground "#666666" :slant italic)))))

  (custom-set-faces
   '(gray-face ((t (:foreground "#575757")))))

  ;; Support for Python
  (defcustom no-distraction--python-rules
    (no-distraction-get-rule 'python
			       ((function_definition)   "def"    @gray-face)
			       ((class_definition)      "class"  @gray-face)
			       ((import_statement)      "import" @gray-face)
			       ((import_from_statement) "from"   @gray-face))
    "Tree-sitter rules for no-distraction in Python."
    :group 'no-distraction)

  (add-to-list 'no-distraction--modes-settings
		 '(python-ts-mode . no-distraction--python-rules))

  ;; Enable automatically for specific modes
  (add-hook 'python-ts-mode-hook #'no-distraction-mode)
#+end_src
** nerd-icons
[[https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/#h:e5e7b781-4b04-4c53-bf23-5e81789549ce][Use icon fonts (specifically nerd-icons..Thanks Prot!)]]
#+begin_src emacs-lisp
  (use-package nerd-icons)

  (use-package nerd-icons-dired
    :hook (dired-mode . nerd-icons-dired-mode))

  (use-package nerd-icons-ibuffer
    ;; Also display nerd-icons for iBuffer types
    :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src
** rainbow-delimiters
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :defer 1
    :config
    (set-face-attribute 'rainbow-delimiters-unmatched-face nil
			:foreground 'unspecified
			:inherit 'error)
    (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))

  (use-package prog-mode
    :straight (:type built-in)
    :hook ((prog-mode . rainbow-delimiters-mode)))
 #+end_src
** rainbow-mode
Display colour codes in the actual colour they represent, e.g. #0000ff (should be white text on a blue background)
#+begin_src emacs-lisp
  (use-package rainbow-mode
    :demand t
    :hook (prog-mode)
    )
#+end_src
** winpulse
[[https://github.com/xenodium/winpulse][GitHub - xenodium/winpulse: Temporarily highlight focused Emacs windows]]
#+begin_src emacs-lisp
  (use-package winpulse
    :straight (:host github :repo "xenodium/winpulse" :files ("*.el"))
    :config
    (winpulse-mode +1))
#+end_src
* Window Management
** bindings
#+begin_src emacs-lisp
  ;; Swap windows (useful for org on left, dired on right (built-in as of 26.1)
  ;; (C-x C-o used to be "delete-blank-lines but i never use that)
  (global-set-key (kbd "C-x C-o") 'window-swap-states)
#+end_src
** zoom
[[https://github.com/cyrus-and/zoom][GitHub - cyrus-and/zoom: Fixed and automatic balanced window layout for Emacs]]
#+begin_src emacs-lisp
  (use-package zoom
    :defer 2
    :config
    (zoom-mode 1))
#+end_src
** zygospore
Toggles between "current" buffer to fullscreen and existing buffer layout (and back again)
#+begin_src emacs-lisp
  (use-package zygospore
    :defer 2
    )
  (global-set-key (kbd "C-x 1") 'zygospore-toggle-delete-other-windows)
#+end_src
* Completion Setup
** company
[[Https://emacs.stackexchange.com/questions/13286/how-can-i-stop-the-enter-key-from-triggering-a-completion-in-company-mode][How can I stop the enter key from triggering a completion in company mode?]]
#+begin_src emacs-lisp
  (use-package company
	:defer 2
	:delight company-mode  ;; Turns off the listing of company mode in list of minor modes (e.g. modeline)
	:init
	(setopt company-idle-delay 0.1
		company-minimum-prefix-length 1)

	:bind (:map company-active-map
	   ("C-n" . company-select-next)
	   ("C-p" . company-select-previous))

	:config
	(global-company-mode))
#+end_src
** consult
#+begin_src emacs-lisp
  (use-package consult
	:defer 2
	:bind
	("C-x b" . consult-buffer) ;; originally 'switch-to-buffer'
	("M-s"   . consult-line)   ;; keep C-s for regular isearch so we can search within a line..
	:config
	(consult-customize
	 consult-theme
	 consult-ripgrep
	 consult-git-grep
	 consult-grep
	 consult-bookmark
	 consult-recent-file
	 consult-xref
	 consult--source-bookmark
	 consult--source-file-register
	 consult--source-recent-file
	 consult--source-project-recent-file
	 :preview-key nil
	)
  )
#+end_src
** marginalia
#+begin_src emacs-lisp
  ;; Enable rich annotations using the Marginalia package
  (use-package marginalia
	:defer 2
	;; Bind `marginalia-cycle' locally in the minibuffer.  To make the
	;; available in the *Completions* buffer, add it to the
	;; `completion-list-mode-map'.
	:bind (:map minibuffer-local-map
	   ("M-A" . marginalia-cycle))

	;; The :init section is always executed.
	:init
	;; Marginalia must be activated in the :init section of use-package such that
	;; the mode gets enabled right away. Note that this forces loading the package.
	(marginalia-mode))
#+end_src
** orderless
Resources:
- [[https://youtu.be/J0OaRy85MOo?feature=shared][Streamline Your Emacs Completions with Vertico - YouTube]]
- [[https://kristofferbalintona.me/posts/202202211546/][Vertico, Marginalia, All-the-icons-completion, and Orderless | Kristoffer Bal...]]
#+begin_src emacs-lisp
  ;; https://github.com/minad/consult/wiki#minads-orderless-configuration
  (use-package orderless
    :config

    (defun +orderless--consult-suffix ()
      "Regexp which matches the end of string with Consult tofu support."
      (if (and (boundp 'consult--tofu-char) (boundp 'consult--tofu-range))
	  (format "[%c-%c]*$"
		  consult--tofu-char
		  (+ consult--tofu-char consult--tofu-range -1))
	"$"))

    ;; Recognizes the following patterns:
    ;; * .ext (file extension)
    ;; * regexp$ (regexp matching at end)
    (defun +orderless-consult-dispatch (word _index _total)
      (cond
       ;; Ensure that $ works with Consult commands, which add disambiguation suffixes
       ((string-suffix-p "$" word)
	`(orderless-regexp . ,(concat (substring word 0 -1) (+orderless--consult-suffix))))
       ;; File extensions
       ((and (or minibuffer-completing-file-name
		 (derived-mode-p 'eshell-mode))
	     (string-match-p "\\`\\.." word))
	`(orderless-regexp . ,(concat "\\." (substring word 1) (+orderless--consult-suffix))))))

    ;; Define orderless style with initialism by default
    (orderless-define-completion-style +orderless-with-initialism
      (orderless-matching-styles '(orderless-initialism orderless-literal orderless-regexp)))

    ;; You may want to combine the `orderless` style with `substring` and/or `basic`.
    ;; There are many details to consider, but the following configurations all work well.
    ;; Personally I (@minad) use option 3 currently. Also note that you may want to configure
    ;; special styles for special completion categories, e.g., partial-completion for files.
    ;;
    ;; 1. (setq completion-styles '(orderless))
    ;; This configuration results in a very coherent completion experience,
    ;; since orderless is used always and exclusively. But it may not work
    ;; in all scenarios. Prefix expansion with TAB is not possible.
    ;;
    ;; 2. (setq completion-styles '(substring orderless))
    ;; By trying substring before orderless, TAB expansion is possible.
    ;; The downside is that you can observe the switch from substring to orderless
    ;; during completion, less coherent.
    ;;
    ;; 3. (setq completion-styles '(orderless basic))
    ;; Certain dynamic completion tables (completion-table-dynamic)
    ;; do not work properly with orderless. One can add basic as a fallback.
    ;; Basic will only be used when orderless fails, which happens only for
    ;; these special tables.
    ;;
    ;; 4. (setq completion-styles '(substring orderless basic))
    ;; Combine substring, orderless and basic.
    ;;
    (setopt completion-styles '(substring orderless basic)
	    completion-category-defaults nil
	    ;; Enable partial-completion for files.
	    ;; Either give orderless precedence or partial-completion.
	    ;; Note that completion-category-overrides is not really an override,
	    ;; but rather prepended to the default completion-styles.
	    ;; completion-category-overrides '((file (styles orderless partial-completion))) ;; orderless is tried first
	    completion-category-overrides '((file (styles partial-completion)) ;; partial-completion is tried first
					    ;; enable initialism by default for symbols
					    (command (styles +orderless-with-initialism))
					    (variable (styles +orderless-with-initialism))
					    (symbol (styles +orderless-with-initialism)))
	    orderless-component-separator #'orderless-escapable-split-on-space ;; allow escaping space with backslash!
	    orderless-style-dispatchers (list #'+orderless-consult-dispatch
					      #'orderless-affix-dispatch)))
#+end_src
** vertico
Resources:
- [[https://youtu.be/J0OaRy85MOo?feature=shared][Streamline Your Emacs Completions with Vertico - YouTube]]
- [[https://kristofferbalintona.me/posts/202202211546/][Vertico, Marginalia, All-the-icons-completion, and Orderless | Kristoffer Bal...]]
#+begin_src emacs-lisp
  (use-package vertico
    :config
    (setopt vertico-cycle         t ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
	    vertico-scroll-margin 0
	    vertico-resize        nil
	    vertico-count         15)
    :hook (after-init vertico-mode)
    )

  ;; Do not allow the cursor in the minibuffer prompt
  (setopt minibuffer-prompt-properties '(read-only t cursor-intangible t face minibuffer-prompt))
  (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)

  ;; Emacs 28: Hide commands in M-x which do not work in the current mode.
  ;; Vertico commands are hidden in normal buffers.
  (setopt read-extended-command-predicate #'command-completion-default-include-p)
#+end_src
* Development Support
** python
- <2025-04-05 Sat> [[https://www.reddit.com/r/emacs/comments/1jqy8xl/python_so_many_lspserver_options_which_one_is_the/][So many lsp-server options. Which one is "the right one"]]
- <2024-12-29 Sun> [[https://mclare.blog/posts/using-uv-in-emacs/][Using uv in Emacs | MClare Blog]]
- <2024-12-29 Sun> [[https://olddeuteronomy.github.io/post/python-programming-in-emacs/][Python Programming in Emacs - The Emacs Cat]] (use pyright from Microsoft instead?)
- <2024-12-22 Sun> Great reference for comprehensive python config: [[https://config.phundrak.com/emacs/packages/programming.html#python][Programming | Phundrak's Dotfiles]]
- [[https://github.com/joaotavora/eglot][GitHub - joaotavora/eglot: A client for Language Server Protocol servers]]
- [[https://ddavis.io/posts/emacs-python-lsp/][Python with Emacs: py(v)env and lsp-mode]]
- [[https://whatacold.io/blog/2022-01-22-emacs-eglot-lsp/][Eglot for better programming experience in Emacs - whatacold's space]]
*** eglot
https://docs.astral.sh/ruff/editors/setup/#via-external-tool
https://grtcdr.tn/dotfiles/emacs/emacs.html#orgdb7d3a6
https://www.reddit.com/r/emacs/comments/190g713/ruff_issues_with_flymake_eglot_and_pythonlspruff/ (problem solving)

When we're ready to use pyright, we can use uvx to do so -> [[https://www.reddit.com/r/emacs/comments/1mddqpx/eglot_pyright_made_simple_thanks_to_uvx/][eglot + pyrights made simple thanks to uvx!]]
#+begin_src emacs-lisp
  ;; Workaround to keep "project" from interfering with "projectile" (which I don't use??)
  (use-package project
    :straight t
    )

  (use-package eglot
    :defer t
    :custom
    (eglot-report-progress nil)

    :config
    (fset #'jsonrpc--log-event #'ignore)

    (setopt jsonrpc-event-hook nil)
    ;; :bind (:map eglot-mode-map
    ;;		("C-c C-o" . eglot-code-action-organize-imports))

    ;; Setup python
    (add-to-list 'eglot-server-programs '(python-mode . ("ruff" "server")))

    ;; <2025-01-24 Fri> Tried the following out but it is WAY to type-picky for my current level of patience
    ;; If we want to try it again: $ pipx install basedpyright
    ;; (add-to-list 'eglot-server-programs '(python-mode . ("~/.local/bin/basedpyright-langserver" "--stdio")))

    )

  (add-hook 'python-ts-mode-hook 'eglot-ensure)
  (add-hook 'python-ts-mode-hook #'outline-indent-minor-mode)
  (add-hook 'python-mode-hook    #'outline-indent-minor-mode)
  (with-eval-after-load 'python
  (define-key python-mode-map (kbd "C-c C-o") #'eglot-code-action-organize-imports))
  ;; "Emacs by default caps the number of bytes read from a subprocess in a single chunk to 4KB.
  ;; However, modern machines can take on a lot more. Set it to 1MB which is equal to the limit
  ;; defined in /proc/sys/fs/pipe-max-size/."
  (setopt read-process-output-max (* 1024 1024))

  ;; (:map eglot-mode-map
  ;;   ("C-c e a" . eglot-code-actions)
  ;;   ("C-c e f" . eglot-format)
  ;;   ("C-c e r" . eglot-rename)
  ;;   ("C-c f d" . flymake-show-project-diagnostics)
  ;;   ("C-c f n" . flymake-goto-next-error)
  ;;   ("C-c f p" . flymake-goto-prev-error)
  ;;   ("C-c x a" . xref-find-apropos)
  ;;   ("C-c x f" . xref-find-definitions)
  ;;   ("C-c x r" . xref-find-references))
#+end_src
*** indent-bars
[[https://github.com/jdtsmith/indent-bars][GitHub - jdtsmith/indent-bars]]
#+begin_src emacs-lisp
  (use-package indent-bars
    :hook ((python-mode python-ts-mode) . indent-bars-mode)
    :custom
    (indent-bars-color                   '(highlight :face-bg t :blend 0.3))
    (indent-bars-pattern                 ".")
    (indent-bars-width-frac              0.2)
    (indent-bars-pad-frac                0.2)
    (indent-bars-prefer-character        t)
    (indent-bars-color-by-depth          '(:regexp "outline-\\([0-9]+\\)" :blend 1))
    (indent-bars-highlight-current-depth '(:blend 0.3))
    )
#+end_src
** envrc
[[https://github.com/purcell/envrc]]
#+begin_src emacs-lisp
  (use-package envrc
    :defer 1
    :config
    (envrc-global-mode)
    )
#+end_src

** dotenv-mode
#+begin_src emacs-lisp
  (load-file "~/.emacs.d/site-lisp/emacs-dotenv-mode/dotenv-mode.el")
#+end_src
** format-all
Auto-format whole buffer, h/t: [[https://ianyepan.github.io/posts/format-all/][Ian YE Pan]]
#+begin_src emacs-lisp
  (use-package format-all
   :commands format-all-mode
   :hook (prog-mode . format-all-mode)
   :config
   (setq-default format-all-formatters '(("Python" (ruff "format"))))
   (setq format-all-show-errors nil))
#+end_src
** treesit-fold
[[https://github.com/emacs-tree-sitter/treesit-fold?tab=readme-ov-file#-method-1-with-straightel-and-use-package][GitHub - emacs-tree-sitter/treesit-fold: Code folding using treesit.el]]
#+begin_src emacs-lisp
  (use-package treesit-fold
    :straight (treesit-fold :type git :host github :repo "emacs-tree-sitter/treesit-fold")
    :init
    (setq treesit-fold-line-count-show t)  ; Show line count in folded regions
    :bind
    ("C-<tab>" . treesit-fold-toggle)
    )
#+end_src
** magit/git
*** magit
#+begin_src emacs-lisp
  (use-package magit
    :demand t

    :bind
    ("C-x C-g" . magit-status)

    :config
    (define-key magit-status-mode-map (kbd "q") 'magit-quit-session)
    (setopt magit-log-margin '(t "%Y-%m-%d %H:%M " magit-log-margin-width t 18)))

  ;; Full screen magit-status
  (defadvice magit-status (around magit-fullscreen activate)
    (window-configuration-to-register :magit-fullscreen)
    ad-do-it
    (delete-other-windows))

  (defun magit-quit-session ()
    "Restores the previous window configuration and kills the magit buffer"
    (interactive)
    (kill-buffer)
    (jump-to-register :magit-fullscreen))

#+end_src
*** COMMENT magit-file-icons (stopped working 2025-11-25)
[[https://github.com/gekoke/magit-file-icons/tree/d85fad81e74a9b6ce9fd7ab341f265d5a181d2a8][Github: magit-file-icons]]
#+begin_src emacs-lisp
  (use-package magit-file-icons
    :after magit

    :straight (:host github :repo "gekoke/magit-file-icons")

    :defer 1

    :init
    (magit-file-icons-mode 1)

    :custom
    ;; These are the default values:
    (magit-file-icons-enable-diff-file-section-icons t)
    (magit-file-icons-enable-untracked-icons         t)
    (magit-file-icons-enable-diffstat-icons          t)
    )

  (setopt magit-format-file-function #'magit-format-file-nerd-icons)
#+end_src
*** git-config-modes
#+begin_src emacs-lisp
(use-package git-modes
  :ensure t)
#+end_src
*** magit-todos
#+begin_src emacs-lisp
  (use-package magit-todos
	:after magit
	:config
	(setopt magit-show-long-lines-warning nil)
	(magit-todos-mode 1)
	)
#+end_src
*** full-frame
Use a single-window (part. for Magit) and then close.
#+begin_src emacs-lisp
  (use-package fullframe
	:defer 1
	:config (fullframe magit-status magit-mode-quit-window)
	)
#+end_src
*** git-timemachine
 #+begin_src emacs-lisp
   (use-package git-timemachine
	 :defer 1
	 )
 #+end_src
*** diff-hl-mode
Ooh..like this much better than git-gutter!
#+begin_src emacs-lisp
  (use-package diff-hl
	:init
	(global-diff-hl-mode)
	)
#+end_src
*** ibuffer-git
#+begin_src emacs-lisp
  (use-package ibuffer-git
	:defer 1
	:after git
	)
#+end_src
** jujutsu
*** COMMENT majutsu-mode
<2026-04-30 Thu> Tried but it couldn't use internal emacs buffer, wanting to use emacsclient
#+begin_src emacs-lisp
  (use-package majutsu
    :straight (:host github :repo "0WD0/majutsu")
    :bind
    ("C-x C-j" . majutsu-log)
    )
#+end_src
***  jj-mode (bolivier)
#+begin_src emacs-lisp
  (use-package jj-mode
    :straight (:host github :repo "bolivier/jj-mode.el")
    :bind
    ("C-x C-j" . jj-log)
    )
#+end_src
** [[https://github.com/gavv/transient-compile?tab=readme-ov-file#installation][transient-compile]]
#+begin_src emacs-lisp
   (straight-use-package 'f)
   (straight-use-package 's)

   (straight-use-package
    '(transient-compile
      :type git
      :host github
      :repo "gavv/transient-compile"
      :branch "main"))

  (defun my-straight-pull-package-tc (package)
     "Pull the latest version of PACKAGE from its remote repository."
     (message "'straight-pull-package-tc' for transient-compile.")
     (straight-pull-package package)
     )
   (add-hook 'emacs-startup-hook (lambda () (my-straight-pull-package-tc 'transient-compile)))

   (defun transient-compile-poe-targets (directory)
     "Get list of targets from a pyproject.toml using poe."
     (when-let* ((executable (transient-compile--tool-property 'poe :exe))
			(command (transient-compile--shell-join
				  executable
				  `("--directory" , directory)
				  )
				 )
			(output (transient-compile--shell-run command))
			(lines (s-lines output)))
       (let (tasks)
		(with-temp-buffer
		  (insert output)
		  (goto-char (point-min))
		  (when (re-search-forward "^CONFIGURED TASKS$" nil t)
		    (forward-line 1)
		    (while (not (eobp))
		      (let ((line (buffer-substring-no-properties
				   (line-beginning-position)
				   (line-end-position))))
			(when (string-match
			       (rx bol (* whitespace)
				   (group (+ (not whitespace)))
				   (+ whitespace))
			       line)
			  (let ((task (match-string 1 line)))
			    (push task tasks)
			    )))
		      (forward-line 1))))
		(nreverse tasks))))

   ;; My feeble (and unsuccessful) attempt at this..
   (defun transient-compile-poe-command (directory target)
     "Format build command for a poe directive."
     (when-let* ((executable (transient-compile--tool-property 'poe :exe)))
       (transient-compile--shell-join executable target)))

   (use-package transient-compile
     :config
     (add-to-list 'transient-compile-tool-alist
		       '(poe :match ("pyproject.toml")
			     :exe "poe"
			     :chdir t
			     :targets transient-compile-poe-targets
			     :command transient-compile-poe-command))
     :custom
     (transient-compile-interactive t)
     )

#+end_src
** COMMENT dumb-jump
<2026-04-30 Thu> Tried to make this work today and gave it, never was able to "override" eglot.
#+begin_src emacs-lisp
  (use-package dumb-jump
    :ensure t
    :custom
    (dumb-jump-prefer-searcher 'rg)
    (dumb-jump-selector        'completing-read) ;; or 'ivy, 'helm, etc.
    :config
    (add-hook 'xref-backend-functions #'dumb-jump-xref-activate))

  (defun my-prefer-dumb-jump ()
    "Prefer dumb-jump over eglot for xref."
    (setq-local xref-backend-functions
		    (cons #'dumb-jump-xref-activate
			  (remove #'dumb-jump-xref-activate xref-backend-functions))))

  (add-hook 'python-mode-hook #'my-prefer-dumb-jump)

  (setq xref-show-definitions-function #'consult-xref)

#+end_src
* FileTypes & Modes
** css
#+begin_src emacs-lisp
  (use-package css-mode
	:defer 2
	:custom
	(css-indent-offset 2))
#+end_src
** csv
#+begin_src emacs-lisp
  (use-package csv-mode
    :defer t
    :init
    (add-to-list 'auto-mode-alist '("\\*.csv$" . csv-mode))
    (add-to-list 'auto-mode-alist '("\\*.tsv$" . csv-mode))
  )
#+end_src
** graphviz-dot-mode
#+begin_src emacs-lisp
  (use-package graphviz-dot-mode
	:defer t
	:config
	(setopt graphviz-dot-indent-width 4))
#+end_src
** justfile
#+begin_src emacs-lisp
  (use-package just-mode
    :defer t
    :config
    (add-to-list 'auto-mode-alist '("\\just$'" . just-mode))
    )
#+end_src
** markdown
*** markdown
Specifically, GithubFlavoredMarkdown-mode
#+begin_src emacs-lisp
  (use-package markdown-mode
	:defer t

	:mode ("*\\.md\\'" . gfm-mode)

	:init
	(setq
	 markdown-command      "multimarkdown"
	 markdown-open-command "/usr/local/bin/mark") ;; Opens application -> Marked2

	:config
	(add-hook 'markdown-mode-hook 'visual-line-mode)
	(add-hook 'markdown-mode-hook 'pb/markdown-config)
	;;(add-hook 'markdown-mode-hook 'pb/variable-width-face-mode)
	)

  (defun pb/markdown-config ()
	(local-set-key (kbd "M-q") 'ignore))
#+end_src
*** olivetti
https://github.com/rnkn/olivetti
#+begin_src emacs-lisp
  (use-package olivetti
	:defer t

	:init
	(setopt olivetti-body-width 0.66)

	:hook
	((markdown-mode . olivetti-mode))
	)
#+end_src
** org
*** org
#+begin_src emacs-lisp
  ;; -----------------------------------------------------------------------------
  ;; Packages
  ;; -----------------------------------------------------------------------------
  (use-package org
    :demand t
    :straight (:type built-in)
    :bind (:map org-mode-map
		    ("C-M-<return>" . org-insert-subheading)
		    ("C-c l"        . org-store-link)
		    ("C-c L"        . org-cliplink) ;; Defined below...
		    ("C-c a"        . org-agenda)
		    ("C-c |"        . org-table-create-or-convert-from-region)
		    ("C-c C-<"      . org-promote-subtree)
		    ("C-c C->"      . org-demote-subtree)
		    ("C-<right>"    . org-metaright)
		    ("C-<left>"     . org-metaleft)
		    )

    :config
    ;; https://sachachua.com/blog/2024/01/org-mode-custom-link-copy-to-clipboard/
    (org-link-set-parameters
     "copy"
     :follow (lambda (link) (kill-new link))
     :export (lambda (_ desc &rest _) desc))

    :init
    (setq fill-column               96  ;; Org won't use the global fill-column, set here explicitly?
	  org-catch-invisible-edits 'show-and-error
	  org-ellipsis              "…" ;; Other options: ▼ …, ↴ ⤵, ▼, ↴, ⬎, ⤷, ⋱
	  org-hide-leading-stars    t
	  org-indent-mode           nil
	  org-return-follows-link   t
	  org-startup-folded        t
	  org-startup-indented      nil ;; Goes hand-in-hand with turning off org-indent-mode above in :config.
	  org-src-tab-acts-natively t
	  org-link-frame-setup      '((file . find-file))) ;; Don't want the default of find-file-other-window
    )

  (add-to-list 'auto-mode-alist '("\\.org$" . org-mode))

  ;; Allow for links like [[file:~/dev/foo][Code]] to open a dired on Return (or C-c C-o)
  ;; https://emacs.stackexchange.com/questions/10426/org-mode-link-to-open-directory-in-dired
  ;; (add-to-list 'org-file-apps '(directory . emacs))

  ;; ---------------------------------------------------------------------------
  ;; GTD Configuration
  ;; ---------------------------------------------------------------------------
  ;; Keywords: For regular TO-DO items in my GTD world -> C-c C-t to select.
  (setopt org-todo-keywords
	      '((sequence
		 "IDEA(i)"
		 "SMDY(o)"
		 "TODO(t)"
		 "SCHD(s)"
		 "WAIT(a)"
		 "WORK(w)"
		 "DONE(x)"
		 "|"
		 )))

  (setopt org-todo-keyword-faces
	      '(
		("TODO" . org-priority) ;; used to be org-warning aka "#fb4933".
		("WORK" . "light green")
		("DONE" . (:foreground "gray30" :strike-through t))
		("SCHD" . "systemBrownColor")
		("WAIT" . "systemBrownColor")
		("IDEA" . "gray80")
		("SMDY" . "systemBrownColor")
		))

  ;; Format of TODO items (defined like this so the entire headline is NOT colored across, just the TODO keyword.)
  ;; (setq org-fontify-todo-headline nil)

  ;; Format of DONE items (defined like this so the entire headline is colored across, not just the DONE keyword.)
  (setopt org-fontify-done-headline t)
  (set-face-attribute 'org-headline-done nil :foreground "gray30" :strike-through t)
  (set-face-attribute 'org-done          nil :foreground "gray30" :strike-through t)

  ;; ---------------------------------------------------------------------------
  ;; Capture templates
  ;; ---------------------------------------------------------------------------
  (define-key global-map (kbd "C-c c") 'org-capture)
  (setopt org-capture-templates
	      '(
		("t" "GTD"      entry (file+headline "/Users/peter/Repository/00-09 System/01 Org/gtd.org" "INBOX") "** TODO %?\n\n")
		("p" "Projects" entry (file          "/Users/peter/Repository/00-09 System/01 Org/projects.org"   ) "* TODO %?\n\n" :prepend t)
		("j" "Journal"  entry (file+datetree "/Users/peter/Repository/00-09 System/01 Org/journal.org"    ) "*** %?")
		))

  ;; Insert date-time stamp like org but everywhere.
  (global-set-key (kbd "C-c .") 'org-time-stamp)

#+end_src
*** babel
#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (js         . t)
     (python     . t)
     (shell      . t)
     (sqlite     . t)
     ))
  (setopt org-confirm-babel-evaluate nil)
#+end_src
**** sql-lite mode
- [[https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-sqlite.html][SQLite Source Code Blocks in Org Mode]]
*** casual
#+begin_src emacs-lisp
  (use-package casual
    :config
    (keymap-set org-mode-map "M-m" #'casual-org-tmenu)
    (keymap-set org-table-fedit-map "M-m" #'casual-org-table-fedit-tmenu)
    )
#+end_src
**** sql-lite mode
- [[https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-sqlite.html][SQLite Source Code Blocks in Org Mode]]
*** company-org-block
Just start a line with "<" and company will provide a set of options for the org src block, e.g. emacs-lisp, python etc.
#+begin_src emacs-lisp
  (use-package company-org-block
    :ensure t
    :custom
    (company-org-block-edit-style 'auto) ;; 'auto, 'prompt, or 'inline
    :hook ((org-mode . (lambda ()
			 (setq-local company-backends '(company-org-block))
			 (company-mode +1)))))
#+end_src
*** sql-lite mode
- [[https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-sqlite.html][SQLite Source Code Blocks in Org Mode]]
*** svg-tag-mode
Inspired by [[https://sophiebos.io/posts/prettifying-emacs-org-mode/#svg-elements][Prettifying Emacs Org Mode | Sophie Bosio]]
#+begin_src emacs-lisp

  (defface pb/svg-org-date
    '((t :height 0.5))
    "My local custom face for use on SVG rendered org-dates.")

  (use-package svg-tag-mode
    :config
    (defconst date-re "[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}")
    (defconst time-re "[0-9]\\{2\\}:[0-9]\\{2\\}")
    (defconst day-re "[A-Za-z]\\{3\\}")
    (defconst day-time-re (format "\\(%s\\)? ?\\(%s\\)?" day-re time-re))

    (defun svg-progress-percent (value)
      (svg-image (svg-lib-concat
		    (svg-lib-progress-bar (/ (string-to-number value) 100.0) nil :margin 0 :stroke 2 :radius 3 :padding 2 :width 11)
		    (svg-lib-tag (concat value "%") nil :stroke 0 :margin 0)) :ascent 'center))

    (defun svg-progress-count (value)
      (let* ((seq (mapcar #'string-to-number (split-string value "/")))
	       (count (float (car seq)))
	       (total (float (cadr seq))))
	  (svg-image (svg-lib-concat
		      (svg-lib-progress-bar (/ count total) nil :margin 0 :stroke 2 :radius 3 :padding 2 :width 11)
		      (svg-lib-tag value nil :stroke 0 :margin 0)) :ascent 'center)))

    (setopt svg-tag-tags
	  `(
	      ;; -----------------------------------------------------------------------------
	      ;; Task priority
	      ;; -----------------------------------------------------------------------------
	      ;; ("\\[#[A-Z]\\]" .
	      ;;  ((lambda (tag) (svg-tag-make tag :face 'org-priority :beg 2 :end -1 :margin 0))))
	      ("\\[#A\\]" . ((lambda (tag) (svg-tag-make "A" :face 'org-priority))))
	      ("\\[#B\\]" . ((lambda (tag) (svg-tag-make "B" :face 'org-level-2))))
	      ("\\[#C\\]" . ((lambda (tag) (svg-tag-make "C" :face 'org-level-3))))
	      ("\\[#D\\]" . ((lambda (tag) (svg-tag-make "D" :face 'org-level-4))))
	      ("\\[#E\\]" . ((lambda (tag) (svg-tag-make "E" :face 'org-level-5))))
	      ("\\[#F\\]" . ((lambda (tag) (svg-tag-make "F" :face 'org-level-6))))

	      ;; -----------------------------------------------------------------------------
	      ;; Progress
	      ;; -----------------------------------------------------------------------------
	      ("\\(\\[[0-9]\\{1,3\\}%\\]\\)" .
	       ((lambda (tag) (svg-progress-percent (substring tag 1 -2)))))

	      ("\\(\\[[0-9]+/[0-9]+\\]\\)" .
	       ((lambda (tag) (svg-progress-count (substring tag 1 -1)))))

	      ;; -----------------------------------------------------------------------------
	      ;; Citation of the form [cite:@Knuth:1984]
	      ;; -----------------------------------------------------------------------------
	      ("\\(\\[cite:@[A-Za-z]+:\\)" .
	       ((lambda (tag) (svg-tag-make tag :inverse t :beg 7 :end -1 :crop-right t))))

	      ("\\[cite:@[A-Za-z]+:\\([0-9]+\\]\\)" .
	       ((lambda (tag) (svg-tag-make tag :end -1 :crop-left t))))

	      ;; -----------------------------------------------------------------------------
	      ;; Active date (with or without day name, with or without time)
	      ;; -----------------------------------------------------------------------------
	      (,(format "\\(<%s>\\)" date-re) .
	       ((lambda (tag) (svg-tag-make tag :beg 1 :end -1 :margin 0 :face 'pb/svg-org-date))))

	      (,(format "\\(<%s \\)%s>" date-re day-time-re) .
	       ((lambda (tag) (svg-tag-make tag :beg 1 :inverse nil :crop-right t :margin 0 :face 'pb/svg-org-date))))

	      (,(format "<%s \\(%s>\\)" date-re day-time-re) .
	       ((lambda (tag) (svg-tag-make tag :end -1 :inverse t :crop-left t :margin 0 :face 'pb/svg-org-date))))

	      ;; -----------------------------------------------------------------------------
	      ;; Inactive date  (with or without day name, with or without time)
	      ;; -----------------------------------------------------------------------------
	      (,(format "\\(\\[%s\\]\\)" date-re) .
	       ((lambda (tag) (svg-tag-make tag :beg 1 :end -1 :margin 0 :face 'pb/svg-org-date))))

	      (,(format "\\(\\[%s \\)%s\\]" date-re day-time-re) .
	       ((lambda (tag) (svg-tag-make tag :beg 1 :inverse nil :crop-right t :margin 0 :face 'pb/svg-org-date))))

	      (,(format "\\[%s \\(%s\\]\\)" date-re day-time-re) .
	       ((lambda (tag) (svg-tag-make tag :end -1 :inverse t :crop-left t :margin 0 :face 'pb/svg-org-date))))

	      ;; -----------------------------------------------------------------------------
	      ;; My development GTD item types (hard to keep from picking up arbitrary "[foo]" entries)
	      ;; -----------------------------------------------------------------------------
	      ("\\[BUG\\]" . ((lambda (tag) (svg-tag-make "BUG" :face 'font-lock-comment-face)))) ;; Bug (duh..)
	      ("\\[ENH\\]" . ((lambda (tag) (svg-tag-make "ENH" :face 'font-lock-comment-face)))) ;; Enhancement
	      ("\\[FIX\\]" . ((lambda (tag) (svg-tag-make "FIX" :face 'font-lock-comment-face)))) ;; FixMe
	      ("\\[HOW\\]" . ((lambda (tag) (svg-tag-make "HOW" :face 'font-lock-comment-face)))) ;; How To
	      ("\\[INF\\]" . ((lambda (tag) (svg-tag-make "INF" :face 'font-lock-comment-face)))) ;; Information
	      ("\\[REF\\]" . ((lambda (tag) (svg-tag-make "REF" :face 'font-lock-comment-face)))) ;; Reference
	      ("\\[SEC\\]" . ((lambda (tag) (svg-tag-make "SEC" :face 'font-lock-comment-face)))) ;; Security
	      ("\\[TST\\]" . ((lambda (tag) (svg-tag-make "TST" :face 'font-lock-comment-face)))) ;; Bug (duh..)
	      )
	  )
    :hook (org-mode-hook . svg-tag-mode)
    )
#+end_src
*** org-appear
Enables /automatic/ visibility toggling depending on cursor position
 #+begin_src emacs-lisp
   (use-package org-appear
     :defer 1
     :after 'org
     :hook (org-mode . org-appear-mode))
 #+end_src
*** COMMENT [[https://github.com/jcguu95/org-linker.el/tree/master?tab=readme-ov-file#customizable-variables][org-linker]]
<2026-02-18 Wed> Not clear how much I use this anymore, save some startup time!
 #+begin_src emacs-lisp
   (defun pb/org-linker/generate-id ()
	 "Generate an id, ie. YYYYMMDD-<id> (thanks GPT-4)."
	 (let ((current-date (format-time-string "%Y%m%d"))
	   (id (replace-regexp-in-string "[[:space:]\n]*$" ""
	 (shell-command-to-string "openssl rand -hex 6"))))
	   (format "%s-%s" current-date id)))

   (straight-use-package
	'(org-linker
	  :type git
	  :host github
	  :repo "jcguu95/org-linker.el"
	  :files ("org-linker.el"
	  "org-linker-commands.el"
	  "org-linker-org-link-support.el"
	  )
	  )
	)
   (load "~/.emacs.d/straight/repos/org-linker.el/org-linker.el")

   (setopt org-linker/root-directory        (concat (getenv "HOME") "/Repository/00-09 System/99 org-linker-storage/")
	 org-linker/file-size               999999
	 org-linker/uuid-generator-function 'pb/org-linker/generate-id
	 org-linker/trashing-function       (lambda (file) (move-file-to-trash file))
	 )
 #+end_src
*** org-cliplink
Create an org-link from a URL in the clipboard with the actual title of the URL as the link title.
 #+begin_src emacs-lisp
   (use-package org-cliplink
     :after 'org
     )
 #+end_src
*** org-superstar
Nicer bullets (replaces org-bullets)
#+begin_src emacs-lisp
  (use-package org-superstar
    :config
    (setopt org-superstar-item-bullet-alist '((?* . ?•) (?+ . ?➤) (?- . ?•)))
    (add-hook 'org-mode-hook (lambda () (org-superstar-mode 1))))
#+end_src
** pdf
#+begin_src emacs-lisp
  (use-package pdf-tools
    :defer 5
    :config
    (setopt pdf-info-epdfinfo-program "/usr/local/bin/epdfinfo")
    )
  (pdf-tools-install)
#+end_src
** toml-mode
#+begin_src emacs-lisp
  (use-package toml-ts-mode
    :defer
    :config
    (add-hook 'toml-ts-mode-hook (lambda() (setopt truncate-lines t) (visual-line-mode -1)))
    )
#+end_src
** typst-mode
#+begin_src emacs-lisp
  (use-package typst-ts-mode
    :straight '(:type git :host codeberg :repo "meow_king/typst-ts-mode")

    :custom
    (typst-ts-watch-options "--open")
    (typst-ts-mode-grammar-location (expand-file-name "tree-sitter/libtree-sitter-typst.so" user-emacs-directory))
    (typst-ts-mode-enable-raw-blocks-highlight t)

    :config
    (keymap-set typst-ts-mode-map "C-c C-c" #'typst-ts-tmenu)

    )

#+end_src
** yaml-mode
#+begin_src emacs-lisp
  (use-package yaml-pro
    :defer t
    :mode ("\\.ya?ml\\'" . yaml-mode)  ;; More idiomatic
    :hook
    (yaml-mode    . yaml-pro-ts-mode)
    (yaml-mode    . (lambda () (setq indent-tabs-mode nil)));; <2025-10-07 Tue> Something was turning ON tab mode for yaml, explicitly kill it!
    (yaml-mode    . outline-indent-minor-mode)
    (yaml-ts-mode . outline-indent-minor-mode)
    )
#+end_src
** web-mode
[[https://web-mode.org][Web-mode documentation]]
#+begin_src emacs-lisp
  (use-package web-mode
    :mode
    (("\\.phtml\\'"    . web-mode)
     ("\\.php\\'"      . web-mode)
     ("\\.tpl\\'"      . web-mode)
     ("\\.htmx\\'"     . web-mode)
     ("\\.html\\'"     . web-mode)
     ("\\.[agj]sp\\'"  . web-mode)
     ("\\.as[cp]x\\'"  . web-mode)
     ("\\.erb\\'"      . web-mode)
     ("\\.mustache\\'" . web-mode)
     ("\\.djhtml\\'"   . web-mode))

    :config
    ;; (add-to-list 'web-mode-engines-alist '(("django" . "\\.html$")))
    ;; (add-to-list 'web-mode-engines-alist '(("django" . "\\.htmx$")))
    ;;
    ;; Copy what we did for IRIS at ES, i.e. have HTML indenting match Python:
    (setopt web-mode-markup-indent-offset 2)
    (setopt web-mode-css-indent-offset    2)
    (setopt web-mode-code-indent-offset   2)
    (setopt web-mode-indent-style         2)

    :hook
    (web-mode . (lambda () (setq indent-tabs-mode nil)))

    )
#+end_src
** tree-sitter
- As of <2023-08-14 Mon> Working 29.1! (from https://github.com/railwaycat/homebrew-emacsmacport)
  (with some help from [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][How to Get Started with Tree-Sitter - Mastering Emacs]])
#+begin_src emacs-lisp
    (setopt treesit-language-source-alist
	    '(
	      (bash       "https://github.com/tree-sitter/tree-sitter-bash")
	      (cmake      "https://github.com/uyha/tree-sitter-cmake")
	      (css        "https://github.com/tree-sitter/tree-sitter-css")
	      (html       "https://github.com/tree-sitter/tree-sitter-html")
	      (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
	      (json       "https://github.com/tree-sitter/tree-sitter-json")
	      (make       "https://github.com/alemuller/tree-sitter-make")
	      (markdown   "https://github.com/ikatyang/tree-sitter-markdown")
	      (python     "https://github.com/tree-sitter/tree-sitter-python")
	      (toml       "https://github.com/tree-sitter/tree-sitter-toml")
	      (yaml       "https://github.com/ikatyang/tree-sitter-yaml"))
	    )

    (use-package treesit-auto
      :config
      (global-treesit-auto-mode)
      )

    (use-package treesit-fold
      :hook (yaml-ts-mode . treesit-fold-mode)
      :bind (:map treesit-fold-mode-map
		  ("C-<tab>" . treesit-fold-toggle-all)
		  ("S-<tab>" . treesit-fold-toggle)))
#+end_src
* External Tools & Services
** aspell
Live spell checking.
NOTE!: This requires a local/manual installation (ie. outside emacs)!
#+begin_src emacs-lisp
  (setopt ispell-program-name "/usr/local/bin/aspell")
  (add-to-list 'ispell-skip-region-alist '("^#+BEGIN_SRC" . "^#+END_SRC"))
#+end_src
** [[https://github.com/karthink/gptel][gptel]]
- Another source with great customisation: https://github.com/certainty/madmacs/blob/main/modules/tools/madmacs-tools-ai.el
- Alternative package to keep an eye on: [[https://github.com/mzacho/claudia][Claudia is an Emacs integration for the Claude AI as...]]
#+begin_src emacs-lisp
    (require 'auth-source)
    (defun pb/get-anthropic-api-key ()
      "Retrieve the API key for api.anthropic.com from .authinfo."
      (require 'auth-source)
      (let ((secret (plist-get (nth 0 (auth-source-search :host "api.anthropic.com"))
				   :secret)))
	      (if secret
	        secret
	      (error "No API key found for api.anthropic.com in .authinfo"))))

    (use-package gptel
      :straight (:host github :repo "karthink/gptel")

      :config
      (setopt gptel-model 'claude-sonnet-4-5-20250929)
      (setopt gptel-backend (gptel-make-anthropic "Claude" :stream t :key (pb/get-anthropic-api-key)))

      ;; Set your custom system prompt:
      (setopt gptel-directives '((default . "Your role is not to agree with me, but to sharpen my thinking. You are my intellectual sparring partner—not just an assistant. Your goal is to help me arrive at the clearest, most accurate version of the truth.
  When I present an idea, proposal, or conclusion, do the following unless
  I explicitly ask you not to:
  - Analyze my assumptions – What am I taking for granted? What might not be true?
  - Provide counterpoints when warranted – What would an intelligent, informed skeptic say?
  - Test my logic – Are there gaps, contradictions, or faulty reasoning?
  - Offer alternative frames – Could this be interpreted, structured, or approached differently?
  - Prioritize truth over agreement – If I'm wrong or missing something, say so. Clearly, and constructively.
  Do not argue for the sake of arguing. Stay constructive, purposeful, and focused on progress. Match your intensity to the moment: challenge hard in decisions and strategy; riff lightly in creative flow—but always keep your edge sharp. If I drift into confirmation bias or flawed logic, call it out.
  ")))

      ;;   (setopt gptel-directives
      ;;	    '((default . "You are a large language model living in Emacs and a helpful assistant.
      ;; Respond concisely. Don't be overly agreeable and act as my brutally
      ;; honest, high-level advisor and mirror. If do you challenge my thinking,
      ;; question my assumptions, or expose the blind spots: be direct but
      ;; friendly. Look at my situation with complete objectivity and strategic
      ;; depth. Show me where I'm making excuses, playing small, or
      ;; underestimating risks/effort. When generating python, use double-quotes
      ;; around all string constants.")))

      :custom
      (gptel-default-mode #'org-mode)
      ;; (gptel-directives
      ;;  '(
      ;;    (default . "You are a large language model living in Emacs and a helpful assistant. Respond concisely. Paragraph lines should be no longer than 120 chars, hard wrap them on your own.")
      ;;    (python . "You are a large language model living in Emacs and a helpful python coding assistant. Respond concisely. Paragraph lines should be no longer than 120 chars, hard wrap them on your own. Python code should use double-quotes for strings.")
      ;;    )
      ;;  )

      ;; ;; https:github.com/DiamondBond/emacs/blob/f9747d9e595518b26d605278144328d73d5d64bf/lisp/gpt.el#L38
      ;; ((default . "You are a large language model and a helpful assistant. Respond concisely.")
      ;;  (reflect . "You are a world-class AI system, capable of complex reasoning and reflection. Reason through the query inside <thinking> tags, and then provide your final response inside <output> tags. If you detect that you made a mistake in your reasoning at any point, correct yourself inside <reflection> tags.")
      ;;  (emacs . "You are a large language model living in Emacs and a helpful assistant. Respond concisely.")
      ;;  (programming . "You are a large language model and a careful programmer. Provide code and only code as output without any additional text, prompt or note.")
      ;;  (typescript . "You are an expert Typescript programmer. Provide code as output.")
      ;;  (writing . "You are a large language model and a writing assistant. Respond concisely.")
      ;;  (chat . "You are a large language model and a conversation partner. Respond concisely."))

      ;; https://github.com/ksqsf/emacs-config/blob/bf7cda793532a5b0a391c74b8f9b55f0e5aaafb2/modules/prelude-ai.el#L31
      ;; (bug . "You are a large language model and a careful programmer. The supplied code doesn't work, or contains bugs. Describe each problem using only one sentence. Provide fixes without changing the old behavior.")
      )

    (defun my-straight-pull-package (package)
      "Pull the latest version of PACKAGE from its remote repository."
      (message "'straight-pull-package' for gptel.")
      (straight-pull-package package)
      )
    (add-hook 'emacs-startup-hook (lambda () (my-straight-pull-package 'gptel)))

    ;; (defun my/gptel-write-buffer ()
    ;;   "Save buffer to disk when starting gptel"
    ;;   ;; Based on discussion with karthink: https://github.com/karthink/gptel/discussions/129
    ;;   (unless (buffer-file-name (current-buffer))
    ;;     (let ((suffix (format-time-string "%Y%m%dT%H%M" (current-time)))
    ;;           (chat-dir "~/Repository"))
    ;;       (unless (file-directory-p chat-dir)
    ;;         (make-directory chat-dir :parents))
    ;;       (write-file (expand-file-name (concat "gptel-" suffix ".org") chat-dir)))))
    ;; (add-hook 'gptel-mode-hook #'my/gptel-write-buffer)

#+end_src
*** Magnus has a cleaner example of using auth-source [potentially rework the code above with this?]
<2024-09-03 Tue> [[https://magnus.therning.org/2024-09-01-improving-how-i-handle-secrets-in-my-work-notes.html][Improving how I handle secrets in my work notes]]:

*Improving how I handle secrets in my work notes*

At work I use org-mode to keep notes about useful ways to query our
systems, mostly that involves using the built-in SQL support to access
DBs and ob-http to send HTTP requests. In both cases I often need to
provide credentials for the systems. I'm embarrassed to admit it, but
for a long time I've taken the easy path and kept all credentials in
clear text. Every time I've used one of those code blocks I've thought
I really ought to find a better way of handling these secrets one of
these days. Yesterday was that day.

I ended up with two functions that uses auth-source and its ~/.authinfo.gpg file.
#+begin_src emacs-lisp
  (defun mes/auth-get-pwd (host)
    "Get the password for a host (authinfo.gpg)"
    (-> (auth-source-search :host host)
	car
	(plist-get :secret)
	funcall))

  (defun mes/auth-get-key (host key)
    "Get a key's value for a host (authinfo.gpg)

  Not usable for getting the password (:secret), use 'mes/auth-get-pwd'
  for that."
    (-> (auth-source-search :host host)
	car
	(plist-get key)))
#+end_src

It turns out that the library can handle more keys than the
documentation suggests so for DB entries I'm using a machine (:host)
that's a bit shorter and easier to remember than the full AWS
hostname. Then I keep the DB host and name in dbhost (:dbhost) and
dbname (:dbname) respectively. That makes an entry look like this:

machine db.svc login user port port password pwd dbname dbname dbhost dbhost
If I use it in a property drawer it looks like this

:PROPERTIES:
:header-args:sql: :engine postgresql
:header-args:sql+: :dbhost (mes/auth-get-key "db.svc" :dbhost)
:header-args:sql+: :dbport (string-to-number (mes/auth-get-key "db.svc" :port))
:header-args:sql+: :dbuser (mes/auth-get-key "db.svc" :user)
:header-args:sql+: :dbpassword (mes/auth-get-pwd "db.svc")
:header-args:sql+: :database (mes/auth-get-key "db.svc" :dbname)
:END:
** [[https://www.jds.work/emacs-prodigy/][prodigy]] (managing local services)
#+begin_src emacs-lisp
  (use-package prodigy
	:defer 1
	)

  (prodigy-define-service
	:name          "OptimusLudos-Server-LocalDatabase"
	:cwd           "~/Repository/10-19 Development/10 Development/10.01 optimus_ludos"
	:command       "~/.local/bin/poe"
	:args          '("dev_run_local")
	:ready-message "Ready..."
	)

  (prodigy-define-service
	:name          "OptimusLudos-Server-ProductionDatabase"
	:cwd           "~/Repository/10-19 Development/10 Development/10.01 optimus_ludos"
	:command       "~/.local/bin/poe"
	:args          '("dev_run_production")
	:ready-message "Ready..."
	)

  (prodigy-define-service
	:name          "CoctioniLibri-Server-LocalDatabase"
	:cwd           "~/Repository/10-19 Development/10 Development/10.23 coctione_libri"
	:command       "~/.local/bin/poe"
	:args          '("dev_run_local")
	:ready-message "Ready..."
	)

  (prodigy-define-service
	:name          "CoctioniLibri-Server-ProductionDatabase"
	:cwd           "~/Repository/10-19 Development/10 Development/10.23 coctione_libri"
	:command       "~/.local/bin/poe"
	:args          '("dev_run_production")
	:ready-message "Ready..."
	)

  (prodigy-define-service
	:name          "HealthActivityDashboard-Shiny"
	:cwd           "~/Repository/10-19 Development/10 Development/10.06 health-activity-dashboard/dashboard-shiny"
	:command       "~/.local/bin/poe"
	:args          '("run")
	:ready-message "Ready..."
	)
#+end_src
** ripgrep/rg
Usage reminder: Use ~wgrep-save-all-buffers~ to save once changes have been committed after editing rg results buffer.
#+begin_src emacs-lisp
  (use-package rg
	:defer 1
	:config
	(rg-enable-menu)
	)
#+end_src
** shell
#+begin_src emacs-lisp
  (setopt explicit-shell-file-name "/usr/local/bin/fish")
  (setopt shell-pushd-regexp "push[d]*")
  (setopt shell-popd-regexp   "pop[d]*")

  ;; Make git work within shell
  (setenv "PAGER"  "/bin/cat")
  ;; (setenv "EDITOR" "/Applications/Emacs.app/Contents/MacOS/bin/emacsclient")
#+end_src
** vterm
Usage reminder: ~C-c C-t~ to place terminal into "buffer" mode obo copy/paste operations.
 #+begin_src emacs-lisp
   (use-package vterm
     :defer t
     :config
     (setopt vterm-timer-delay 0.01)
     (setopt vterm-shell "/usr/local/bin/fish")
     :hook
     ((vterm-mode . (lambda () (setq-local show-trailing-whitespace nil)))
      (vterm-mode . pb-hook/vterm-text-scale)
      ;; (vterm-mode . pb-hook/vterm-custom-font-size)
      )
     :custom
     (vterm-always-compile-module t))

   (defun pb-hook/vterm-text-scale()
	 "Sue me...I like to see more text in my terminal windows."
	 (text-scale-set -1))

   (defun pb-hook/vterm-custom-font-size()
	 "Sue me...I like to see more text in my terminal windows."
	 (setopt buffer-face-mode-face '(:weight light :height 220))
	 (buffer-face-mode))

   (defun pb/vterm-current-directory ()
	 "Create a terminal buffer from the current directory."
	 (interactive)
	 (let ((shell-name (car (last (butlast (split-string default-directory "/"))))))
	   (vterm (concat "@" shell-name))
	   )
	 )

   (defun pb/vterm-by-name ()
	 "Create a terminal buffer based on name provided."
	 (interactive)
	 (let ((shell-name (read-string "Shell name: ")))
	   (vterm (concat "@" shell-name))
	   )
	 )
#+end_src
* Custom Commands
These are custom commands I used on regular basis (almost all of which are cribbed from others, credit given as much as possible!). Listed in no particular order:
** change case of text
[[http://ergoemacs.org/emacs/modernization_upcase-word.html]]
#+begin_src emacs-lisp
  (defun pb/toggle-letter-case ()
	"Toggle the letter case of current word or text selection, toggles between: “all lower”, “Init Caps”, “ALL CAPS”."
	(interactive)
	(let (p1 p2 (deactivate-mark nil) (case-fold-search nil))
	  (if (region-active-p)
	      (setq p1 (region-beginning) p2 (region-end))
	  (let ((bds (bounds-of-thing-at-point 'word) ) )
	      (setq p1 (car bds) p2 (cdr bds)) ) )

	  (when (not (eq last-command this-command))
	  (save-excursion
	      (goto-char p1)
	      (cond
	       ((looking-at "[[:lower:]][[:lower:]]") (put this-command 'state "all lower"))
	       ((looking-at "[[:upper:]][[:upper:]]") (put this-command 'state "all caps") )
	       ((looking-at "[[:upper:]][[:lower:]]") (put this-command 'state "init caps") )
	       ((looking-at "[[:lower:]]") (put this-command 'state "all lower"))
	       ((looking-at "[[:upper:]]") (put this-command 'state "all caps") )
	       (t (put this-command 'state "all lower") ) ) )
	  )

	  (cond
	   ((string= "all lower" (get this-command 'state))
	  (upcase-initials-region p1 p2) (put this-command 'state "init caps"))
	   ((string= "init caps" (get this-command 'state))
	  (upcase-region p1 p2) (put this-command 'state "all caps"))
	   ((string= "all caps" (get this-command 'state))
	  (downcase-region p1 p2) (put this-command 'state "all lower")) )
	  )
	)

  ;; Turn these off so they don't interfere with our custom method
  (put 'downcase-region 'disabled nil)
  (put 'upcase-region   'disabled nil)

  (global-set-key (kbd "M-l") 'pb/toggle-letter-case) ;; Overrides existing mapping
#+end_src
** ctrl-a behaviour enhancement
Ctrl-a goes to *logical beginning* of line first before a second invocation takes point to *physical* beginning.
#+begin_src emacs-lisp
  (defun pb/key-back-to-indentation-or-beginning ()
	(interactive)
	(if (= (point) (progn (back-to-indentation) (point)))
	(beginning-of-line)))
  (global-set-key (kbd "C-a") 'pb/key-back-to-indentation-or-beginning)
#+end_src
** ctrl-g a bit more helpful
[[https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/#h:1e468b2a-9bee-4571-8454-e3f5462d9321][Make ctrl-g a bit more helpful]] (Thanks Prot!)
#+begin_src emacs-lisp
  (defun pb/keyboard-quit-dwim ()
    "Do-What-I-Mean behaviour for a general `keyboard-quit'.

  The generic `keyboard-quit' does not do the expected thing when
  the minibuffer is open.  Whereas we want it to close the
  minibuffer, even without explicitly focusing it.

  The DWIM behaviour of this command is as follows:

  - When the region is active, disable it.
  - When a minibuffer is open, but not focused, close the minibuffer.
  - When the Completions buffer is selected, close it.
  - In every other case use the regular `keyboard-quit'."
    (interactive)
    (cond
     ((region-active-p)
      (keyboard-quit))
     ((derived-mode-p 'completion-list-mode)
      (delete-completion-window))
     ((> (minibuffer-depth) 0)
      (abort-recursive-edit))
     (t
      (keyboard-quit))))

  (global-set-key [remap keyboard-quit] #'pb/keyboard-quit-dwim)

#+end_src
** smarter C-w (backward word kill)
[[https://github.com/magnars/.emacs.d/blob/master/defuns/editing-defuns.el]]
#+begin_src emacs-lisp
  ;; Here's a better C-w (kill region if active, otherwise kill backward word)
  (defun pb/kill-region-or-backward-word ()
	(interactive)
	(if (region-active-p)
	(kill-region (region-beginning) (region-end))
	  (backward-kill-word 1)))
  (global-set-key (kbd "C-w") (lambda () (interactive) (pb/kill-region-or-backward-word)))
#+end_src
** better mark-word
[[https://www.emacs.dyerdwelling.family/emacs/20231209092556-emacs--redefining-mark-paragraph-and-mark-word/]]
#+begin_src emacs-lisp
  (defun pb/mark-word()
	"redefinition of mark-word"
	(interactive)
	(if (not (looking-at "\\<"))
	  (backward-word))
	(push-mark)
	(forward-word)
	(setq mark-active t))

  ;; Override existing keymapping
  (global-set-key (kbd "M-@") 'pb/mark-word)
#+end_src
** toggle window split
https://macowners.club/posts/custom-functions-5-navigation/
#+begin_src emacs-lisp
  (defun pb/toggle-split-direction ()
	"Toggle window split from vertical to horizontal or vice-versa.
	 Credit: https://github.com/olivertaylor/dotfiles/blob/master/emacs/init.el"
	(interactive)
	(if (> (length (window-list)) 2)
	(error "Sorry, can only toggle split direction with 2 windows.")
	  (let ((was-full-height (window-full-height-p)))
	(delete-other-windows)
	(if was-full-height
	(split-window-vertically)
	  (split-window-horizontally))
	(save-selected-window
	  (other-window 1)
	  (switch-to-buffer (other-buffer)))))
	)

  (global-set-key (kbd "C-x O") 'pb/toggle-split-direction)
#+end_src
** kill this buffer
[[http://pragmaticemacs.com/emacs/dont-kill-buffer-kill-this-buffer-instead/]]
#+begin_src emacs-lisp
  ;; Kill *this* buffer
  (defun pb/-kill-this-buffer- ()
	"Kill the current buffer."
	(interactive)
	(kill-buffer (current-buffer)))

  (global-set-key (kbd "C-x k") 'pb/-kill-this-buffer-)
#+end_src
** use project-file-find instead of file-find:
#+begin_src emacs-lisp
  (global-set-key (kbd "C-c C-f") #'find-file)
  (global-set-key (kbd "C-x C-f") #'project-find-file)
#+end_src
** flexible find-file
https://www.emacs.dyerdwelling.family/emacs/20240804075952-emacs--finding-files-using-completing-read/
#+begin_src emacs-lisp
  (defun pb/find-file ()
    "Find file from current directory in many different ways."
    (interactive)
    (let* ((find-options '(("find -type f -printf \"$PWD/%p\\0\"" . :string)
			   ("fd --absolute-path --type f -0" . :string)
			   ("rg --follow --files --null" . :string)
			   ("find-name-dired" . :command)))
	   (selection (completing-read "Select : " find-options))
	   (metadata '((category . file)))
	   (file-list)
	   (file))
      (pcase (alist-get selection find-options nil nil #'string=)
	(:command
	 (call-interactively (intern selection)))
	(:string
	 (setq file-list (split-string (shell-command-to-string selection) "\0" t))
	 (setq file (completing-read (format "Find file in %s: " (abbreviate-file-name default-directory))
				     (lambda (str pred action)
				       (if (eq action 'metadata)
					   `(metadata . ,metadata)
					 (complete-with-action action file-list str pred)))
				     nil t nil 'file-name-history)))
	(when file (find-file (expand-file-name file))))))
#+end_src
** scroll page without moving cursor
#+begin_src emacs-lisp
  (global-set-key "\M-n" (lambda () (interactive) (scroll-up 12)))
  (global-set-key "\M-p" (lambda () (interactive) (scroll-down 12)))
#+end_src
** split current frame into evenly balanced "3"
#+begin_src emacs-lisp
  (fset 'pb/split3 (kmacro-lambda-form [?\C-x ?1 ?\C-x ?3 ?\C-x ?3 ?\C-x ?+] 0 "%d"))
#+end_src
** interactive text/font scaling
#+begin_src emacs-lisp
  (defun pb/change-font-size (size)
    "Change font size (clearly `:height` in `face-attribute`) to given SIZE."
    (interactive
     (list
      (read-number
       (format "Input font size (current=%d): " (face-attribute 'default :height))
       nil)))
    (set-face-attribute 'default nil :height size)
    )
  (global-set-key (kbd "C-+") 'pb/change-font-size)
#+end_src
** use Insert key to toggle overwrite/insert
[[https://emacs.stackexchange.com/questions/18533/how-to-use-the-insert-key-to-toggle-overwrite-mode-when-using-a-pc-keyboard-in]]
#+begin_src emacs-lisp
  (when (eq system-type 'darwin)
	;; when using Windows keyboard on Mac, the insert key is mapped to <help>
	;; copy ctrl-insert, paste shift-insert on windows keyboard
	(global-set-key [C-help] #'clipboard-kill-ring-save)
	(global-set-key [S-help] #'clipboard-yank)

	;; insert to toggle `overwrite-mode'
	(global-set-key [help] #'overwrite-mode))
#+end_src
** easier navigation direds of images
Allows us to browse directories of images with simply left-right arrows.
#+begin_src emacs-lisp
(defun kill-buffer-and-move-down ()
  "Kill current buffer, move to next line in dired, and open it."
  (interactive)
  (kill-buffer)
  (when (eq major-mode 'dired-mode)
    (dired-next-line 1)
    (dired-find-file)))

(defun kill-buffer-and-move-up ()
  "Kill current buffer, move to previous line in dired, and open it."
  (interactive)
  (kill-buffer)
  (when (eq major-mode 'dired-mode)
    (dired-previous-line 1)
    (dired-find-file)))

;; Bind arrow keys only in image-mode
(add-hook 'image-mode-hook
	  (lambda ()
	    (local-set-key (kbd "<right>") 'kill-buffer-and-move-down)
	    (local-set-key (kbd "<left>") 'kill-buffer-and-move-up)))
#+end_src
* Startup
Stuff we do these after everything else has been setup so we have commands available for key-mappings
** function key mappings
Some of these are baked into my fingers from more than three decades
(anymore remember SPF on IBM Mainframes or the Brief editor on the
first IBM PC's?)...thus, we won't be changing these often.
#+begin_src emacs-lisp
  (global-set-key (kbd "<f1>") 'goto-line)
  (global-set-key (kbd "<f2>") 'toggle-truncate-lines)
  (global-set-key (kbd "<f3>") 'align-regexp)

  ;; <f4> still available after all these years!

  (global-set-key (kbd   "<f5>") 'rg-project) ;; This one only works on selected text BUT doesn't prompt for directory or file type!
  (global-set-key (kbd "C-<f5>") 'rg-literal) ;; While this one prompts for something to query on but also asks for directory and type as well..

  (global-set-key (kbd   "<f6>") 'anzu-query-replace)
  (global-set-key (kbd "C-<f6>") 'anzu-query-replace-regexp)

  (global-set-key (kbd "<f7>") 'kmacro-start-macro) ; Keyboard macro shortcuts
  (global-set-key (kbd "<f8>") 'kmacro-end-macro)
  (global-set-key (kbd "<f9>") 'call-last-kbd-macro)

  (global-set-key (kbd "<f10>") 'transient-compile) ; Override menu-bar-open (have *never* used it!)

  ;; <f11> still available! (but used by MacOS to hide all windows and display desktop.)

  (global-set-key (kbd   "<f12>") 'pb/vterm-current-directory)
  (global-set-key (kbd "C-<f12>") 'pb/vterm-by-name)
#+end_src
* COMMENT HISTORY (for sh_ts and giggles)
|------------+-------------------------------------------------------------------|
| 1990.07.13 | Make Systems (on Sunview).                                        |
| 1991.06.07 | Teknekron (X using twm).                                          |
| 1993.12.08 | Teknekron (emacs version 19).                                     |
| 1994.03.26 | Added tcl initialisation logic.                                   |
| 2006.01.08 | First real cleanup since the mid-90's (!).                        |
| 2006.10.02 | Configured into AXA Rosenberg.                                    |
| 2008.01.19 | Update/cleanup, addition of ECB, OrgMode.                         |
| 2011.04.15 | Added multiplatform support for Ubuntu & MacOS.                   |
| 2011.09.05 | Updated OrgMode for another attempt at GTD.                       |
| 2011.09.05 | Final tweaks obo EnergySolutions environment.                     |
| 2012.08.15 | Added support for Ropemacs & Pymacs for python IDE.               |
| 2012.08.28 | Added support for GRIN integration.                               |
| 2013.05.12 | Declaring dotemacs-bankruptcy! Moving to site-start architecture. |
| 2020.06.10 | Test and discard of lsp, rebuilt venv for elpy (~/emacs-venv)     |
| 2021.01.04 | Clean up of emacs folders.                                        |
| 2021.11.28 | Moved to PARA file organisation for all main directories.         |
| 2022.03.15 | Moved to support numbered file repository structure.              |
| 2022.11.21 | Part of emacs bankruptcy and move to clean use-package approach.  |
| 2024.03.02 | Cleanup of old/unused packages and store archived "history".      |
|------------+-------------------------------------------------------------------|
* COMMENT ARCHIVED
These are here so I don't waste time in the future trying to use 'em *again*.
** afterglow
[[https://github.com/ernstvanderlinden/emacs-afterglow/tree/8254dc5d4fdfec63e1b5b2d59af0771d2c5a5474][GitHub - ernstvanderlinden/emacs-afterglow at 8254dc5d4fdfec63e1b5b2d59af0771...]]
#+begin_src emacs-lisp
  (use-package afterglow
	:config
	(afterglow-mode t)
	;; Optional customizations
	(setopt afterglow-default-duration 1.0)
	(setopt afterglow-default-face 'hl-line)
	;; Add triggers as needed
	(afterglow-add-triggers
	 '((previous-line     :thing line   :duration 0.2)
	   (next-line         :thing line   :duration 0.2)
	   (eval-buffer       :thing window :duration 0.2)
	   (eval-defun        :thing defun  :duration 0.2)
	   (eval-expression   :thing sexp   :duration 1)
	   (eval-last-sexp    :thing sexp   :duration 1)
	   (my-function       :thing my-region-function :duration 0.5 :face 'highlight))))
#+end_src
** buffer-management
[[https://github.com/alphapapa/bufler.el][GitHub - alphapapa/bufler.el: A butler for your buffers. Group buffers into w...]]
Verdict: too "busy" with many different projects' files open. Easier to simply "s f" in ibuffer to group by path if desired.
#+begin_src emacs-lisp
  (use-package bufler
	:defer t
	)
#+end_src
** co-pilot
https://github.com/copilot-emacs/copilot.el
#+begin_src emacs-lisp
  ;; For some reason, even though I'm on version 30+, this won't work:
  ;; Error (use-package): Failed to parse package copilot: use-package: Unrecognized keyword: :vc
  ;; For now, stay with regular straight pull from github for the time being.
  ;; (use-package copilot
  ;;   :vc (:url "https://github.com/copilot-emacs/copilot.el"
  ;;             :rev :newest
  ;;             :branch "main")
  ;;   :config
  ;;   (add-hook 'prog-mode-hook 'copilot-mode)
  ;;   )
  (use-package copilot
    :straight (:host github :repo "copilot-emacs/copilot.el" :files ("*.el"))
    )
#+end_src
** dashboard (from the "dashboard" package)
#+begin_src emacs-lisp
  (use-package dashboard
    :config
    (setopt dashboard-banner-logo-title "Good Morning Mr. Phelps..."
	    dashboard-center-content            t           ;; Content is not centered by default, we want it to be.
	    dashboard-vertically-center-content t           ;; Vertically center content.
	    dashboard-display-icons-p           t           ;; Display icons on both GUI and terminal
	    dashboard-icon-type                 'nerd-icons ;; Use `nerd-icons' package
	  )
    (setopt dashboard-items '((recents . 15)))
    (setopt dashboard-startupify-list '(dashboard-insert-banner
					dashboard-insert-newline
					dashboard-insert-banner-title
					dashboard-insert-newline
					dashboard-insert-navigator
					dashboard-insert-newline
					dashboard-insert-init-info
					dashboard-insert-items)) ;; Default EXCEPT we don't want the footer.
    (dashboard-setup-startup-hook)
    )
#+end_src
** dbml
<2026-02-01 Sun> Don't use anymore, archive.
#+begin_src emacs-lisp
  (load-file "~/.emacs.d/site-lisp/dbd-mode/dbdiagram-mode.el")
#+end_src
** dired-du
Like the functionality but will NEVER remember C-x M-R to invoke it!
#+begin_src emacs-lisp
  (use-package dired-du
    :ensure t
    :commands dired-du-mode
    :config (setq dired-du-size-format t))
#+end_src
** editorconfig
"EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs."
However, I don't work with "multiple developers" much anymore, not necessary!
[[https://editorconfig.org/][EditorConfig]]
#+begin_src emacs-lisp
  (use-package editorconfig
	:init
	(editorconfig-mode 1)
	)
#+end_src
** elm-mode
On hiatus until/if I get back to doing elm development
https://github.com/jcollard/elm-mode
#+begin_src emacs-lisp
  (use-package elm-mode
	:config
	(setopt elm-format-on-save t)

	:init
	(add-hook 'elm-mode-hook 'elm-format-on-save-mode)
	)
#+end_src
** git-gutter
Stopped usage on 2024-07-10 after replacing with diff-hl.
#+begin_src emacs-lisp
  ;; (use-package git-gutter
  ;;   :straight (:build t)
  ;;   :defer 1
  ;;   :init
  ;;   (global-git-gutter-mode +1)
  ;;   :config
  ;;   (setq git-gutter:disabled-modes '(org-mode image-mode))
  ;;   )
#+end_src
** find-file-in-project
~project-find-file~ works fine, no need to ffip for me.
** focus
[[https://github.com/larstvei/Focus][GitHub - larstvei/Focus: Dim the font color of text in surrounding paragraphs]]
Doesn't work that well with python (for instance, imports are always grey)
 #+begin_src emacs-lisp
   (use-package focus
	 :config
	 (add-to-list 'focus-mode-to-thing '(python-ts-mode . paragraph))
	 )
#+end_src
** inhibit-mouse
Tried..worked well but I lost the ability to scroll back quickly in a terminal window
(frankly, the only time I actually use the mouse, i.e. the only place I desparately missed it!)
[[https://github.com/jamescherti/inhibit-mouse.el][jamescherti/inhibit-mouse.el: Disable the mouse in Emacs]]
(simply toggle ~inhibit-mouse-mode~ to get it back if absolutely necessary)
#+begin_src emacs-lisp
  (use-package inhibit-mouse
    :straight (inhibit-mouse
	       :type git
	       :host github
	       :repo "jamescherti/inhibit-mouse.el")
    :config
    (inhibit-mouse-mode))
#+end_src
** lin
[[https://elpa.gnu.org/packages/lin.html][GNU ELPA - lin]] (Prot)
#+begin_src emacs-lisp
  (use-package lin
    :config
    (lin-global-mode 1)
    )
#+end_src
** magit-delta
<2024-05-31 Fri> Took this out...I actually LIKE the old school diff display!
Use the wonderful delta diff tool in magit diff display.
#+begin_src emacs-lisp
  (use-package magit-delta
	:after magit
	:hook (magit-mode . magit-delta-mode))
#+end_src
** mode-lines
Tried and discarded for one reason or another.
*** telephone-line
*** [[https://github.com/TheBB/spaceline][spaceline]]
[[https://github.com/TheBB/spaceline#turning-segments-on-and-off][GitHub - TheBB/spaceline: Powerline theme from Spacemacs]]
#+begin_src emacs-lisp
  (use-package spaceline
	:disabled
	:init
	(spaceline-emacs-theme)
	:config
	(spaceline-toggle-minor-modes-off)
	)
#+end_src
*** [[https://github.com/Malabarba/smart-mode-line/][smart-mode-line]]
#+begin_src emacs-lisp
  (use-package smart-mode-line
    :disabled
    :init
    (sml/setup)
    )
#+end_src
*** [[https://emacs.dyerdwelling.family/emacs/20230902114449-emacs--my-evolving-modeline/][My Evolving Modeline (Dywer)]]
#+begin_src emacs-lisp
  (setq-default mode-line-modified
	      '(:eval (if (and (buffer-file-name) (buffer-modified-p))
			  (propertize " * Modified " 'face '(:background "#e20023" :foreground "#ffffff")) "")))
  (set-face-attribute 'mode-line-active nil   :height 1.0 :background "#ffffff" :foreground "#000000") ; was 125
  (set-face-attribute 'mode-line-inactive nil :height 0.7 :background "#000000" :foreground "#ffffff")
  (set-face-attribute 'mode-line nil          :height 120)
  (set-face-attribute 'mode-line-inactive nil :height 120)

  (setq-default mode-line-format
	      '("%e"
		mode-line-modified
		(:eval
		 (if (buffer-file-name)
		     (if (mode-line-window-selected-p)
			 (propertize (format "%s " (abbreviate-file-name (buffer-file-name)))
				     'face '(:background "#6b91c0" :foreground "#ffffff" :inherit bold))
		       (format "%s " (abbreviate-file-name (buffer-file-name)))
		       )
		   )
		 )
		(:eval
		 (if (mode-line-window-selected-p)
		     (propertize "%o %4l %2c %b"
				 'face '(:background "#b8b8b8" :foreground "#000000"))
		   "%o %4l %2c %b"))
		(vc-mode vc-mode)
		;; mode-line-modes
		)
	      )

  (setopt mode-line-compact t)
#+end_src
*** maple
Could never get it really installed!
#+begin_src emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-maple-modeline")
  (require 'maple-modeline)
  ;; standard, minimal, sidebar, evil
  (setq maple-modeline-style 'standard)
  ;; modeline style for side window
  (setq maple-modeline-side-style 'side)
  ;; standard or auto or some number
  (setq maple-modeline-width 'standard)
  ;; set modeline height
  (setq maple-modeline-height 20)
  ;; show icon, require nerd-icons package
  ;; (setq maple-modeline-icon (and (display-graphic-p) *icon*))
  ;; the separator of segments
  (setq maple-modeline-separator (if (display-graphic-p) 'arrow 'default))
  ;; separator's direction of left-segments and right-segments: auto,right,left
  (setq maple-modeline-direction '(right . left))

  (maple-modeline-mode)
#+end_src
*** mood-line
Nice and simple based on: https://github.com/jessiehildebrandt/mood-line
#+begin_src emacs-lisp
  (use-package mood-line
    :init
    (custom-set-faces
     '(mode-line-active   ((t (:family "SauceCodePro Nerd Font Mono" :height 1.0))))
     '(mode-line-inactive ((t (:family "SauceCodePro Nerd Font Mono" :height 0.7))))
     )
    (mood-line-mode)
    )
#+end_src
** move-text
#+begin_src emacs-lisp
  (use-package move-text
	:init
	(move-text-default-bindings)
	)
#+end_src
** org-modern-indent
 #+begin_src emacs-lisp
   (use-package org-modern-indent
	 :straight (org-modern-indent :type git :host github :repo "jdtsmith/org-modern-indent")
	 :config
	 (add-hook 'org-mode-hook #'org-modern-indent-mode 128)
   )
 #+end_src
** outli
Never could get this to work :-(
#+begin_src emacs-lisp
  (use-package outli
	:straight (outli :type git :host github :repo "jdtsmith/outli")
	:bind
	(:map outli-mode-map ; convenience key to get back to containing heading
	  ("C-c C-p" . (lambda () (interactive) (outline-back-to-heading))))
	:custom (outli-heading-config '((python-mode     "## " ?* nil nil)
	(emacs-lisp-mode ";; " ?* nil nil)
	))
	:hook ((prog-mode python-mode text-mode) . outli-mode)
	)
#+end_src
** page-break-lines
[[https://github.com/purcell/page-break-lines][Display a nice line for ^L's.]]
#+begin_src emacs-lisp
  (use-package page-break-lines
	:init (global-page-break-lines-mode))
#+end_src
** python (pet)
As of now, not sure when this would be necessary, everything *I* need to do works!
[[https://github.com/wyuenho/emacs-pet][GitHub - wyuenho/emacs-pet: Tracks down the correct Python tooling executable...]]
** python
Get our docstrings and comments to look a bit more different.
--> <2024-12-29 Sun> Can't get this to work properly & consistently... :-(

#+begin_src emacs-lisp
  (use-package python
    :mode ("\\.py\\'" . python-ts-mode)

    :config
    (defface my-python-docstring-face
      '((t (:family "Monaspace Radon" :height 200 :foreground "grey75"))) ; i.e. 2 less than the default size above.
      "Face for Python docstrings and comments.")

    (setopt python-ts-mode-hook
	  (lambda ()
	    (setq-local treesit-font-lock-settings
			(append
			 (treesit-font-lock-rules

			  :language 'python
			  :feature  'comment
			'((comment) @font-lock-comment-face)

			  :language 'python
			  :feature  'docstring
			  '((string) @my-python-docstring-face))

			 treesit-font-lock-settings))

	    (treesit-font-lock-recompute-features))))

  (add-to-list 'major-mode-remap-alist '(python-mode . python-ts-mode))
#+end_src
** poetry
#+begin_src emacs-lisp
  (use-package poetry
    :defer t
    :config
    (setopt poetry-tracking-strategy 'switch-buffer) ;; Checks for the correct virtualenv. Better strategy IMO because the default one is quite slow.
    :hook (python-mode . poetry-tracking-mode))
#+end_src
** postgresql
<2025-07-04 Fri> Turn off as don't use SQL that much anymore and this doesn't seem complete!
#+begin_src emacs-lisp
  (setopt sql-postgres-program "/Applications/Postgres.app/Contents/Versions/latest/bin/psql")
  (add-hook 'sql-mode-hook 'sql-highlight-postgres-keywords)
  (add-hook 'sql-interactive-mode-hook 'sql-rename-buffer)

  ;; Execute this after opening up SQL to get a scratch
  ;; buffer from which to submit sql with C-c C-b
  (defun pgsql-scratch ()
	(interactive)
	(switch-to-buffer "*scratch*")
	(sql-mode)
	(sql-set-product "postgres")
	(sql-set-sqli-buffer)
	(sql-rename-buffer)
	)

  (defun upcase-sql-keywords ()
	(interactive)
	(save-excursion
	  (dolist (keywords sql-mode-postgres-font-lock-keywords)
	(goto-char (point-min))
	(while (re-search-forward (car keywords) nil t)
	  (goto-char (+ 1 (match-beginning 0)))
	  (when (eql font-lock-keyword-face (face-at-point))
	(backward-char)
	(upcase-word 1)
	(forward-char))))))

  (setopt sql-connection-alist
	  '(
	(foo
	(sql-product 'postgres)
	(sql-port 5432)
	(sql-server "localhost")
	(sql-user "--sorry, getme from environment--")
	(sql-password "--sorry, getme from environment also--")
	(sql-database "db-foo"))
	   )
	  )

  (defun wrapper-sql-connect (product connection)
	(setopt sql-product product)
	(sql-connect connection))

  ; Startup wrappers
  (defun sql-environment-foo ()
	(interactive)
	(wrapper-sql-connect 'postgres 'foo))
#+end_src
** pyvenv-auto
#+begin_src emacs-lisp
  ;; ref: https://grtcdr.tn/dotfiles/emacs/emacs.html#orgdb7d3a6
  (use-package pyvenv-auto
    :defer 1
    :custom
    (pyvenv-auto-mode t)
    )
#+end_src
** pulsar
[[https://protesilaos.com/emacs/pulsar]]
#+begin_src emacs-lisp
    (defface pb/pulsar-color
      '((t :extend t :inverse-video t :background "#ffe7ba"))
      "My custom color, HT to github: dwang2010/emacs")

    (use-package pulsar
	:init
	(pulsar-global-mode 1)

	:config
	(setopt pulsar-pulse t)
	(setopt pulsar-delay 0.10)
	(setopt pulsar-face  'pb/pulsar-color)

	(dolist (hook '(org-mode-hook python-ts-mode-hook yaml-mode-hook text-mode-hook emacs-lisp-mode-hook dired-mode-hook web-mode-hook))
	  (add-hook hook #'pulsar-mode))

	(add-hook 'next-error-hook #'pulsar-pulse-line)
	)
#+end_src
** smarter open line
<2025-02-25 Tue> Want M-o to be on behalf of change-outer from above "change-inner" package.
 [[http://emacsredux.com/blog/2013/03/26/smarter-open-line/]]
#+begin_src emacs-lisp
  (defun pb/key-smart-open-line ()
    "Insert an empty line after the current line. Position the cursor at its beginning, according to the current mode."
    (interactive)
    (move-end-of-line nil)
    (newline-and-indent))

  (defun pb/key-smart-open-line-above ()
    "Insert an empty line above the current line. Position the cursor at it's beginning, according to the current mode."
    (interactive)

    (move-beginning-of-line nil)
    (newline-and-indent)
    (forward-line -1)
    (indent-according-to-mode))

  (global-set-key (kbd "M-o") 'pb/key-smart-open-line)
  (global-set-key (kbd "M-O") 'pb/key-smart-open-line-above)
#+end_src
** split-windows
I want my split windows to do something different. Seldom do I want to
simply show another location in the current buffer, rather, it's
almost always to get to another file. Let's do this explicitly.

On further reflection, I've gotten so used to the split-window
commands in their old incarnation, I find this new behaviour
"sup-optimal".
#+begin_src emacs-lisp
  (defun my-split-window-dired (split-function)
    "Split window using SPLIT-FUNCTION and open dired in current directory."
    (let ((current-dir (if buffer-file-name
			   (file-name-directory buffer-file-name)
			 default-directory)))
      (funcall split-function)
      (other-window 1)
      (dired current-dir)))

  (defun my-split-window-right-dired ()
    "Split window right and open dired in current directory."
    (interactive)
    (my-split-window-dired 'split-window-right))

  (defun my-split-window-below-dired ()
    "Split window below and open dired in current directory."
    (interactive)
    (my-split-window-dired 'split-window-below))

  ;; Replace the default split-window commands
  (global-set-key (kbd "C-x 3") 'my-split-window-right-dired)
  (global-set-key (kbd "C-x 2") 'my-split-window-below-dired)
#+end_src
** substitute
https://protesilaos.com/emacs/substitute
#+begin_src emacs-lisp
  (use-package substitute
	:config
	(require 'substitute)
	(add-hook 'substitute-post-replace-functions #'substitute-report-operation)

	:bind (("M-<f6>" . substitute-target-in-buffer))
	)
#+end_src
** theme: hercules
Like it but couldn't get the code below to work (custom-theme-set-faces not defined? etc.)
#+begin_src emacs-lisp
  (add-to-list 'custom-theme-load-path "~/.emacs.d/site-lisp/hercules-theme/")
  (use-package hercules-theme
    :demand t
    :config
    (load-theme 'hercules t)
    :custom-theme-set-faces
     'user
     '(org-level-1            ((t (:height 1.15))))
     '(org-level-2            ((t (:height 1.10))))
     '(org-level-3            ((t (:height 1.05))))
     '(org-level-4            ((t (:foreground "#b8bb26"))))
     '(org-level-5            ((t (:foreground "#fb4933"))))
     '(font-lock-doc-face     ((t (:foreground "#666666"))))
     '(font-lock-comment-face ((t (:foreground "#666666"))))
     '(org-document-title     ((t (:height 1.5 :underline nil)))))
#+end_src
** theme: modus-operandi (light-theme)
#+begin_src emacs-lisp
  (use-package modus-themes
    :demand t
    :config
    ;;
    ;; Use Prot's own configuration:
    ;; https://protesilaos.com/emacs/modus-themes#h:aabcada6-810d-4eee-b34a-d2a9c301824d
    ;;
    (setq modus-themes-custom-auto-reload nil
  modus-themes-to-toggle         '(modus-operandi modus-vivendi)
  modus-themes-mixed-fonts       t
  modus-themes-variable-pitch-ui nil
  modus-themes-italic-constructs t
  modus-themes-bold-constructs   t
  modus-themes-org-blocks        'gray-background
  modus-themes-completions       '((t . (extrabold)))
  modus-themes-prompts           nil
  )

    (setq modus-themes-common-palette-overrides
    '((cursor magenta-cooler)

    ;; Make the fringe invisible.
    (fringe unspecified)

    ;; Make line numbers less intense and add a shade of cyan
    ;; for the current line number.
    (fg-line-number-inactive "gray50")
    (fg-line-number-active cyan-cooler)
    (bg-line-number-inactive unspecified)
    (bg-line-number-active unspecified)

    ;; Make the current line of `hl-line-mode' a fine shade of
    ;; gray (though also see my `lin' package).
    (bg-hl-line bg-dim)

    ;; Make the region have a cyan-green background with no
    ;; specific foreground (use foreground of underlying text).
    ;; "bg-sage" refers to Salvia officinalis, else the common
    ;; sage.
    (bg-region bg-sage)
    (fg-region unspecified)

    ;; Make matching parentheses a shade of magenta. It complements the region nicely.
    (bg-paren-match bg-magenta-intense)

    ;; Change dates to a set of more subtle combinations.
    (date-deadline  magenta-cooler)
    (date-scheduled magenta)
    (date-weekday   fg-main)
    (date-event     fg-dim)
    (date-now       blue-faint)

    ;; Make tags (Org) less colorful and tables look the same as
    ;; the default foreground.
    (prose-done  cyan-cooler)
    (prose-tag   fg-dim)
    (prose-table fg-main)

    ;; Make headings less colorful (though I never use deeply
    ;; nested headings).
    (fg-heading-2 blue-faint)
    (fg-heading-3 magenta-faint)
    (fg-heading-4 blue-faint)
    (fg-heading-5 magenta-faint)
    (fg-heading-6 blue-faint)
    (fg-heading-7 magenta-faint)
    (fg-heading-8 blue-faint)

    ;; Make the active mode line a fine shade of lavender and tone down the gray of the inactive mode lines.
    (bg-mode-line-active       bg-lavender)
    (border-mode-line-active   bg-lavender)
    (bg-mode-line-inactive     bg-dim)
    (border-mode-line-inactive bg-inactive)

    ;; Make the prompts a shade of magenta, to fit in nicely with the overall blue-cyan-purple style of the other overrides.
    ;; Add a nuanced background as well.
    (bg-prompt bg-magenta-nuanced)
    (fg-prompt magenta-cooler)

    ;; Tweak some more constructs for stylistic constistency.
    (name       blue-warmer)
    (identifier magenta-faint)
    (keybind    magenta-cooler)
    (accent-0   magenta-cooler)
    (accent-1   cyan-cooler)
    (accent-2   blue-warmer)
    (accent-3   red-cooler)
    )
  )

    ;; Make the active mode line have a pseudo 3D effect (this assumes
    ;; you are using the default mode line and not an extra package).
    (custom-set-faces
     '(mode-line ((t :box (:style released-button)))))

    (load-theme 'modus-operandi t)
    )
#+end_src
** theme: monokai
#+begin_src emacs-lisp
  (use-package monokai
	:config
	(setq monokai-height-plus-4 1.2
	  monokai-height-plus-3 1.1
	 )
	(load-theme 'monokai nil)
  )
#+end_src
** theme: [[https://protesilaos.com/emacs/ef-themes][ef-autumn]]
#+begin_src emacs-lisp
  (use-package ef-themes
	:config
	(setq ef-themes-italic-constructs t
	  ef-themes-bold-constructs nil)
	(setq ef-themes-headings
	  '((0 . (0.8))			;; Document titles etc.
	(1 . (1.2))
	(2 . (1.1))))
	(setq ef-themes-common-palette-overrides
	  '((fg-heading-1 blue)
	(fg-heading-2 cyan)
	(fg-heading-3 green)))
	(load-theme 'ef-autumn)
  )
#+end_src
** theme: flexoki
#+begin_src emacs-lisp
  (use-package flexoki-themes
	:config
	(load-theme 'flexoki-themes-dark t)
	:custom
	(flexoki-themes-use-bold-keywords t)
	(flexoki-themes-use-bold-builtins t)
	(flexoki-themes-use-italic-comments t))
#+end_src
** theme: nano
#+begin_src emacs-lisp
  (use-package nano-theme
	:config
	(load-theme 'nano t))
#+end_src
** treesit-auto
As of <2024-08-28 Wed> and migration to emacs30, I don't think we need this anymore.
[[https://github.com/renzmann/treesit-auto][GitHub - renzmann/treesit-auto: Automatic installation, usage, and fallback f...]]
#+begin_src emacs-lisp
  (use-package treesit-auto
	:defer 1

	:config
	(global-treesit-auto-mode)
	(setq treesit-auto-install t)
	)
#+end_src
** [[https://github.com/jdtsmith/ultra-scroll][ultrascroll]]
<2026-01-21 Wed> Not sure this is working on my build, removing for the time being.
 #+begin_src emacs-lisp
   (use-package ultra-scroll
     :straight (ultra-scroll :type git :host github :repo "jdtsmith/ultra-scroll" :files ("*.el"))
     :init
     (setopt scroll-conservatively 101 ; important!
	   scroll-margin 0)
     :config
     (ultra-scroll-mode 1))
#+end_src
** ws-butler
#+begin_src emacs-lisp
  (use-package ws-butler
	:config
	(ws-butler-global-mode 1)
  )
#+end_src
